// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { paths as GeneratedPaths, operations as GeneratedOperations } from "./internal/generated/local-api.js";

export const PeasantLocalAPIVersion = "0.3.0" as const;

export type paths = GeneratedPaths;
export type operations = GeneratedOperations;
