// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { components } from "./internal/generated/types.js";

export const TypesVersion = "0.2.0" as const;

export type ActivityEdge = components["schemas"]["ActivityEdge"];
export type AnnotationEntryTarget = components["schemas"]["AnnotationEntryTarget"];
export type AnnotationManifestResponse = components["schemas"]["AnnotationManifestResponse"];
export type AnnotationPushItem = components["schemas"]["AnnotationPushItem"];
export type AnnotationPushRequest = components["schemas"]["AnnotationPushRequest"];
export type AnnotationPushResponse = components["schemas"]["AnnotationPushResponse"];
export type AnnotationPushResult = components["schemas"]["AnnotationPushResult"];
export type AnnotationSummary = components["schemas"]["AnnotationSummary"];
export type AnnotationTypeSummary = components["schemas"]["AnnotationTypeSummary"];
export type AnnotationsPayload = components["schemas"]["AnnotationsPayload"];
export type AnnotatorSummary = components["schemas"]["AnnotatorSummary"];
export type BatchCreateAnnotationsErrorResponse = components["schemas"]["BatchCreateAnnotationsErrorResponse"];
export type BatchCreateAnnotationsRequest = components["schemas"]["BatchCreateAnnotationsRequest"];
export type BatchCreateAnnotationsResponse = components["schemas"]["BatchCreateAnnotationsResponse"];
export type CLILoginQuery = components["schemas"]["CLILoginQuery"];
export type ChangeDetailPayload = components["schemas"]["ChangeDetailPayload"];
export type ChangeDiffPayload = components["schemas"]["ChangeDiffPayload"];
export type ChangeSession = components["schemas"]["ChangeSession"];
export type ChangeSummary = components["schemas"]["ChangeSummary"];
export type ChannelSubscription = components["schemas"]["ChannelSubscription"];
export type ChildSessionRef = components["schemas"]["ChildSessionRef"];
export type ClientMessage = components["schemas"]["ClientMessage"];
export type CommitInfo = components["schemas"]["CommitInfo"];
export type CommitRef = components["schemas"]["CommitRef"];
export type ContractVersion = components["schemas"]["ContractVersion"];
export type CreateAnnotationRequest = components["schemas"]["CreateAnnotationRequest"];
export type CreateAnnotationResponse = components["schemas"]["CreateAnnotationResponse"];
export type DashboardPayload = components["schemas"]["DashboardPayload"];
export type DayStats = components["schemas"]["DayStats"];
export type DiagnosticEntry = components["schemas"]["DiagnosticEntry"];
export type DiagnosticsInfo = components["schemas"]["DiagnosticsInfo"];
export type DiffHunk = components["schemas"]["DiffHunk"];
export type DiffLine = components["schemas"]["DiffLine"];
export type EdgeViolation = components["schemas"]["EdgeViolation"];
export type ExchangeCodeRequest = components["schemas"]["ExchangeCodeRequest"];
export type ExchangeCodeResponse = components["schemas"]["ExchangeCodeResponse"];
export type FamiliarityPayload = components["schemas"]["FamiliarityPayload"];
export type FileChange = components["schemas"]["FileChange"];
export type FileFamiliarity = components["schemas"]["FileFamiliarity"];
export type FrictionCluster = components["schemas"]["FrictionCluster"];
export type GitContext = components["schemas"]["GitContext"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type HostSlug = components["schemas"]["HostSlug"];
export type MapEdge = components["schemas"]["MapEdge"];
export type MapGraphPayload = components["schemas"]["MapGraphPayload"];
export type MapNode = components["schemas"]["MapNode"];
export type MapNodeDetailPayload = components["schemas"]["MapNodeDetailPayload"];
export type MapSlice = components["schemas"]["MapSlice"];
export type MockConfigResponse = components["schemas"]["MockConfigResponse"];
export type ModelID = components["schemas"]["ModelID"];
export type ModelInfo = components["schemas"]["ModelInfo"];
export type ProjectContext = components["schemas"]["ProjectContext"];
export type ProjectHash = components["schemas"]["ProjectHash"];
export type ProjectSummariesPayload = components["schemas"]["ProjectSummariesPayload"];
export type ProjectSummary = components["schemas"]["ProjectSummary"];
export type ProjectTasksPayload = components["schemas"]["ProjectTasksPayload"];
export type Provenance = components["schemas"]["Provenance"];
export type PublishRequest = components["schemas"]["PublishRequest"];
export type PublishResponse = components["schemas"]["PublishResponse"];
export type PullAnnotation = components["schemas"]["PullAnnotation"];
export type PullListResponse = components["schemas"]["PullListResponse"];
export type PullSkipGateItem = components["schemas"]["PullSkipGateItem"];
export type PullSkipGateRequest = components["schemas"]["PullSkipGateRequest"];
export type PullSkipGateResponse = components["schemas"]["PullSkipGateResponse"];
export type PullSkipGateResult = components["schemas"]["PullSkipGateResult"];
export type PullTranscriptInfo = components["schemas"]["PullTranscriptInfo"];
export type QualityMetrics = components["schemas"]["QualityMetrics"];
export type QualityPayload = components["schemas"]["QualityPayload"];
export type QualitySession = components["schemas"]["QualitySession"];
export type RedactionInfo = components["schemas"]["RedactionInfo"];
export type ReviewListPayload = components["schemas"]["ReviewListPayload"];
export type ReviewSuggestion = components["schemas"]["ReviewSuggestion"];
export type SchemaVersionResponse = components["schemas"]["SchemaVersionResponse"];
export type SearchPayload = components["schemas"]["SearchPayload"];
export type SearchResult = components["schemas"]["SearchResult"];
export type ServerMessage = components["schemas"]["ServerMessage"];
export type SessionDetailPayload = components["schemas"]["SessionDetailPayload"];
export type SessionEntry = components["schemas"]["SessionEntry"];
export type SessionID = components["schemas"]["SessionID"];
export type SessionIdentity = components["schemas"]["SessionIdentity"];
export type SessionScorecard = components["schemas"]["SessionScorecard"];
export type SessionStats = components["schemas"]["SessionStats"];
export type SessionSummary = components["schemas"]["SessionSummary"];
export type SessionsPayload = components["schemas"]["SessionsPayload"];
export type ShutdownResponse = components["schemas"]["ShutdownResponse"];
export type SourceInfo = components["schemas"]["SourceInfo"];
export type SubagentRef = components["schemas"]["SubagentRef"];
export type TaskSummary = components["schemas"]["TaskSummary"];
export type TaxonomyFamilyNode = components["schemas"]["TaxonomyFamilyNode"];
export type TaxonomyNode = components["schemas"]["TaxonomyNode"];
export type TimestampInfo = components["schemas"]["TimestampInfo"];
export type ToolCallDetail = components["schemas"]["ToolCallDetail"];
export type TranscriptContent = components["schemas"]["TranscriptContent"];
export type TranscriptID = components["schemas"]["TranscriptID"];
export type TrendsPayload = components["schemas"]["TrendsPayload"];
export type TurnDetail = components["schemas"]["TurnDetail"];
export type UnifiedMetadata = components["schemas"]["UnifiedMetadata"];
export type UnusualSignal = components["schemas"]["UnusualSignal"];
export type ValueDomain = components["schemas"]["ValueDomain"];
export type WalkthroughStep = components["schemas"]["WalkthroughStep"];
export type WalkthroughTrail = components["schemas"]["WalkthroughTrail"];

export type PushContractVersion = ContractVersion;
export const MetadataSchemaVersion = 9 as const;

export const AnnotationAxis = Object.freeze({
  Type: "type",
  Session: "session",
  Project: "project",
} as const);
export type AnnotationAxis = (typeof AnnotationAxis)[keyof typeof AnnotationAxis];
export const AllAnnotationAxes = Object.freeze([AnnotationAxis.Type, AnnotationAxis.Session, AnnotationAxis.Project] as const satisfies readonly AnnotationAxis[]);
export function isAnnotationAxis(value: unknown): value is AnnotationAxis {
  return typeof value === "string" && (Object.values(AnnotationAxis) as readonly string[]).includes(value);
}

export const AnnotationDatatype = Object.freeze({
  Text: "text",
  Integer: "integer",
  Real: "real",
  Boolean: "boolean",
} as const);
export type AnnotationDatatype = (typeof AnnotationDatatype)[keyof typeof AnnotationDatatype];
export const AllAnnotationDatatypes = Object.freeze([AnnotationDatatype.Text, AnnotationDatatype.Integer, AnnotationDatatype.Real, AnnotationDatatype.Boolean] as const satisfies readonly AnnotationDatatype[]);
export function isAnnotationDatatype(value: unknown): value is AnnotationDatatype {
  return typeof value === "string" && (Object.values(AnnotationDatatype) as readonly string[]).includes(value);
}

export const AnnotationPushStatus = Object.freeze({
  Created: "created",
  Updated: "updated",
  Skipped: "skipped",
  Error: "error",
} as const);
export type AnnotationPushStatus = (typeof AnnotationPushStatus)[keyof typeof AnnotationPushStatus];
export const AllAnnotationPushStatuses = Object.freeze([AnnotationPushStatus.Created, AnnotationPushStatus.Updated, AnnotationPushStatus.Skipped, AnnotationPushStatus.Error] as const satisfies readonly AnnotationPushStatus[]);
export function isAnnotationPushStatus(value: unknown): value is AnnotationPushStatus {
  return typeof value === "string" && (Object.values(AnnotationPushStatus) as readonly string[]).includes(value);
}

export const AnnotationStatus = Object.freeze({
  Proposed: "proposed",
  Active: "active",
  Deprecated: "deprecated",
  Retired: "retired",
} as const);
export type AnnotationStatus = (typeof AnnotationStatus)[keyof typeof AnnotationStatus];
export const AllAnnotationStatuses = Object.freeze([AnnotationStatus.Proposed, AnnotationStatus.Active, AnnotationStatus.Deprecated, AnnotationStatus.Retired] as const satisfies readonly AnnotationStatus[]);
export function isAnnotationStatus(value: unknown): value is AnnotationStatus {
  return typeof value === "string" && (Object.values(AnnotationStatus) as readonly string[]).includes(value);
}

export const AnnotatorKind = Object.freeze({
  Human: "human",
  Agent: "agent",
  Rule: "rule",
} as const);
export type AnnotatorKind = (typeof AnnotatorKind)[keyof typeof AnnotatorKind];
export const AllAnnotatorKinds = Object.freeze([AnnotatorKind.Human, AnnotatorKind.Agent, AnnotatorKind.Rule] as const satisfies readonly AnnotatorKind[]);
export function isAnnotatorKind(value: unknown): value is AnnotatorKind {
  return typeof value === "string" && (Object.values(AnnotatorKind) as readonly string[]).includes(value);
}

export const BuiltinCommand = Object.freeze({
  Exit: "exit",
  Compact: "compact",
  Clear: "clear",
  New: "new",
  Model: "model",
  Usage: "usage",
  Cost: "cost",
  Context: "context",
  Plugin: "plugin",
  Permissions: "permissions",
  Login: "login",
  Resume: "resume",
  Plan: "plan",
  Fast: "fast",
  Voice: "voice",
  Todos: "todos",
  ReloadPlugins: "reload-plugins",
  Sandbox: "sandbox",
  Config: "config",
  Statusline: "statusline",
  Upgrade: "upgrade",
  ExtraUsage: "extra-usage",
  RateLimitOptions: "rate-limit-options",
  PrivacySettings: "privacy-settings",
  Help: "help",
  Commands: "commands",
} as const);
export type BuiltinCommand = (typeof BuiltinCommand)[keyof typeof BuiltinCommand];
export const AllClaudeBuiltinCmds = Object.freeze([BuiltinCommand.Exit, BuiltinCommand.Compact, BuiltinCommand.Clear, BuiltinCommand.New, BuiltinCommand.Model, BuiltinCommand.Usage, BuiltinCommand.Cost, BuiltinCommand.Context, BuiltinCommand.Plugin, BuiltinCommand.Permissions, BuiltinCommand.Login, BuiltinCommand.Resume, BuiltinCommand.Plan, BuiltinCommand.Fast, BuiltinCommand.Voice, BuiltinCommand.Todos, BuiltinCommand.ReloadPlugins, BuiltinCommand.Sandbox, BuiltinCommand.Config, BuiltinCommand.Statusline, BuiltinCommand.Upgrade, BuiltinCommand.ExtraUsage, BuiltinCommand.RateLimitOptions, BuiltinCommand.PrivacySettings, BuiltinCommand.Help, BuiltinCommand.Commands] as const satisfies readonly BuiltinCommand[]);
export function isBuiltinCommand(value: unknown): value is BuiltinCommand {
  return typeof value === "string" && (Object.values(BuiltinCommand) as readonly string[]).includes(value);
}

export const ChangeBinding = Object.freeze({
  Bound: "bound",
  Candidate: "candidate",
} as const);
export type ChangeBinding = (typeof ChangeBinding)[keyof typeof ChangeBinding];
export const AllChangeBindings = Object.freeze([ChangeBinding.Bound, ChangeBinding.Candidate] as const satisfies readonly ChangeBinding[]);
export function isChangeBinding(value: unknown): value is ChangeBinding {
  return typeof value === "string" && (Object.values(ChangeBinding) as readonly string[]).includes(value);
}

export const ChannelTopic = Object.freeze({
  Dashboard: "dashboard",
  Sessions: "sessions",
  SessionDetail: "session_detail",
  Trends: "trends",
  Quality: "quality",
  Annotations: "annotations",
  ProjectFamiliarity: "project_familiarity",
} as const);
export type ChannelTopic = (typeof ChannelTopic)[keyof typeof ChannelTopic];
export const AllChannelTopics = Object.freeze([ChannelTopic.Dashboard, ChannelTopic.Sessions, ChannelTopic.SessionDetail, ChannelTopic.Trends, ChannelTopic.Quality, ChannelTopic.Annotations, ChannelTopic.ProjectFamiliarity] as const satisfies readonly ChannelTopic[]);
export function isChannelTopic(value: unknown): value is ChannelTopic {
  return typeof value === "string" && (Object.values(ChannelTopic) as readonly string[]).includes(value);
}

export const ContentKind = Object.freeze({
  SessionDetail: "session_detail",
} as const);
export type ContentKind = (typeof ContentKind)[keyof typeof ContentKind];
export const AllContentKinds = Object.freeze([ContentKind.SessionDetail] as const satisfies readonly ContentKind[]);
export function isContentKind(value: unknown): value is ContentKind {
  return typeof value === "string" && (Object.values(ContentKind) as readonly string[]).includes(value);
}

export const DecayLevel = Object.freeze({
  Fresh: "fresh",
  Fading: "fading",
  Stale: "stale",
  Unexplored: "unexplored",
} as const);
export type DecayLevel = (typeof DecayLevel)[keyof typeof DecayLevel];
export const AllDecayLevels = Object.freeze([DecayLevel.Fresh, DecayLevel.Fading, DecayLevel.Stale, DecayLevel.Unexplored] as const satisfies readonly DecayLevel[]);
export function isDecayLevel(value: unknown): value is DecayLevel {
  return typeof value === "string" && (Object.values(DecayLevel) as readonly string[]).includes(value);
}

export const EdgeViolationKind = Object.freeze({
  Cycle: "cycle",
  WrongWay: "wrong_way",
} as const);
export type EdgeViolationKind = (typeof EdgeViolationKind)[keyof typeof EdgeViolationKind];
export const AllEdgeViolationKinds = Object.freeze([EdgeViolationKind.Cycle, EdgeViolationKind.WrongWay] as const satisfies readonly EdgeViolationKind[]);
export function isEdgeViolationKind(value: unknown): value is EdgeViolationKind {
  return typeof value === "string" && (Object.values(EdgeViolationKind) as readonly string[]).includes(value);
}

export const EntryType = Object.freeze({
  Text: "text",
  ToolUse: "tool_use",
  ToolResult: "tool_result",
  Thinking: "thinking",
  System: "system",
  Error: "error",
  Result: "result",
} as const);
export type EntryType = (typeof EntryType)[keyof typeof EntryType];
export const AllEntryTypes = Object.freeze([EntryType.Text, EntryType.ToolUse, EntryType.ToolResult, EntryType.Thinking, EntryType.System, EntryType.Error, EntryType.Result] as const satisfies readonly EntryType[]);
export function isEntryType(value: unknown): value is EntryType {
  return typeof value === "string" && (Object.values(EntryType) as readonly string[]).includes(value);
}

export const Harness = Object.freeze({
  ClaudeCode: "claude-code",
  GeminiCLI: "gemini-cli",
  Codex: "codex",
  OpenCode: "opencode",
  Cursor: "cursor",
  Antigravity: "antigravity",
} as const);
export type Harness = (typeof Harness)[keyof typeof Harness];
export const AllHarnesses = Object.freeze([Harness.ClaudeCode, Harness.GeminiCLI, Harness.Codex, Harness.OpenCode, Harness.Cursor] as const satisfies readonly Harness[]);
export function isHarness(value: unknown): value is Harness {
  return typeof value === "string" && (Object.values(Harness) as readonly string[]).includes(value);
}

export const InteractionType = Object.freeze({
  Mentioned: "mentioned",
  Read: "read",
  Discussed: "discussed",
  Questioned: "questioned",
} as const);
export type InteractionType = (typeof InteractionType)[keyof typeof InteractionType];
export const AllInteractionTypes = Object.freeze([InteractionType.Mentioned, InteractionType.Read, InteractionType.Discussed, InteractionType.Questioned] as const satisfies readonly InteractionType[]);
export function isInteractionType(value: unknown): value is InteractionType {
  return typeof value === "string" && (Object.values(InteractionType) as readonly string[]).includes(value);
}

export const License = Object.freeze({
  CC0: "CC0-1.0",
  CCBY: "CC-BY-4.0",
  CCBYSA: "CC-BY-SA-4.0",
} as const);
export type License = (typeof License)[keyof typeof License];
export const AllLicenses = Object.freeze([License.CC0, License.CCBY, License.CCBYSA] as const satisfies readonly License[]);
export function isLicense(value: unknown): value is License {
  return typeof value === "string" && (Object.values(License) as readonly string[]).includes(value);
}

export const MapNodeKind = Object.freeze({
  Module: "module",
  Package: "package",
  File: "file",
} as const);
export type MapNodeKind = (typeof MapNodeKind)[keyof typeof MapNodeKind];
export const AllMapNodeKinds = Object.freeze([MapNodeKind.Module, MapNodeKind.Package, MapNodeKind.File] as const satisfies readonly MapNodeKind[]);
export function isMapNodeKind(value: unknown): value is MapNodeKind {
  return typeof value === "string" && (Object.values(MapNodeKind) as readonly string[]).includes(value);
}

export const MessageType = Object.freeze({
  Subscribe: "subscribe",
  Unsubscribe: "unsubscribe",
  Dashboard: "dashboard",
  Sessions: "sessions",
  SessionDetail: "session_detail",
  Trends: "trends",
  Quality: "quality",
  Annotations: "annotations",
  ProjectFamiliarity: "project_familiarity",
  Connected: "connected",
  Error: "error",
} as const);
export type MessageType = (typeof MessageType)[keyof typeof MessageType];
export const AllMessageTypes = Object.freeze([MessageType.Subscribe, MessageType.Unsubscribe, MessageType.Dashboard, MessageType.Sessions, MessageType.SessionDetail, MessageType.Trends, MessageType.Quality, MessageType.Annotations, MessageType.ProjectFamiliarity, MessageType.Connected, MessageType.Error] as const satisfies readonly MessageType[]);
export function isMessageType(value: unknown): value is MessageType {
  return typeof value === "string" && (Object.values(MessageType) as readonly string[]).includes(value);
}

export const Role = Object.freeze({
  User: "user",
  Assistant: "assistant",
  Tool: "tool",
  System: "system",
} as const);
export type Role = (typeof Role)[keyof typeof Role];
export const AllRoles = Object.freeze([Role.User, Role.Assistant, Role.Tool, Role.System] as const satisfies readonly Role[]);
export function isRole(value: unknown): value is Role {
  return typeof value === "string" && (Object.values(Role) as readonly string[]).includes(value);
}

export const ScaleKind = Object.freeze({
  Nominal: "nominal",
  Ordinal: "ordinal",
  Continuous: "continuous",
} as const);
export type ScaleKind = (typeof ScaleKind)[keyof typeof ScaleKind];
export const AllScaleKinds = Object.freeze([ScaleKind.Nominal, ScaleKind.Ordinal, ScaleKind.Continuous] as const satisfies readonly ScaleKind[]);
export function isScaleKind(value: unknown): value is ScaleKind {
  return typeof value === "string" && (Object.values(ScaleKind) as readonly string[]).includes(value);
}

export const SessionOutcome = Object.freeze({
  Resolved: "resolved",
  Partial: "partial",
  Failed: "failed",
} as const);
export type SessionOutcome = (typeof SessionOutcome)[keyof typeof SessionOutcome];
export const AllOutcomes = Object.freeze([SessionOutcome.Resolved, SessionOutcome.Partial, SessionOutcome.Failed] as const satisfies readonly SessionOutcome[]);
export function isSessionOutcome(value: unknown): value is SessionOutcome {
  return typeof value === "string" && (Object.values(SessionOutcome) as readonly string[]).includes(value);
}

export const SourceFormat = Object.freeze({
  JSONL: "jsonl",
  JSON: "json",
} as const);
export type SourceFormat = (typeof SourceFormat)[keyof typeof SourceFormat];
export const AllSourceFormats = Object.freeze([SourceFormat.JSONL, SourceFormat.JSON] as const satisfies readonly SourceFormat[]);
export function isSourceFormat(value: unknown): value is SourceFormat {
  return typeof value === "string" && (Object.values(SourceFormat) as readonly string[]).includes(value);
}

export const StopReason = Object.freeze({
  EndTurn: "end_turn",
  Cancelled: "cancelled",
  MaxTokens: "max_tokens",
  MaxTurnRequests: "max_turn_requests",
  Refusal: "refusal",
} as const);
export type StopReason = (typeof StopReason)[keyof typeof StopReason];
export const AllStopReasons = Object.freeze([StopReason.EndTurn, StopReason.Cancelled, StopReason.MaxTokens, StopReason.MaxTurnRequests, StopReason.Refusal] as const satisfies readonly StopReason[]);
export function isStopReason(value: unknown): value is StopReason {
  return typeof value === "string" && (Object.values(StopReason) as readonly string[]).includes(value);
}

export const TargetKind = Object.freeze({
  Session: "session",
  Entry: "entry",
  Annotation: "annotation",
  Project: "project",
} as const);
export type TargetKind = (typeof TargetKind)[keyof typeof TargetKind];
export const AllTargetKinds = Object.freeze([TargetKind.Session, TargetKind.Entry, TargetKind.Annotation, TargetKind.Project] as const satisfies readonly TargetKind[]);
export function isTargetKind(value: unknown): value is TargetKind {
  return typeof value === "string" && (Object.values(TargetKind) as readonly string[]).includes(value);
}

export const ToolCallKind = Object.freeze({
  Read: "read",
  Edit: "edit",
  Delete: "delete",
  Move: "move",
  Search: "search",
  Execute: "execute",
  Think: "think",
  Fetch: "fetch",
  Other: "other",
} as const);
export type ToolCallKind = (typeof ToolCallKind)[keyof typeof ToolCallKind];
export const AllToolCallKinds = Object.freeze([ToolCallKind.Read, ToolCallKind.Edit, ToolCallKind.Delete, ToolCallKind.Move, ToolCallKind.Search, ToolCallKind.Execute, ToolCallKind.Think, ToolCallKind.Fetch, ToolCallKind.Other] as const satisfies readonly ToolCallKind[]);
export function isToolCallKind(value: unknown): value is ToolCallKind {
  return typeof value === "string" && (Object.values(ToolCallKind) as readonly string[]).includes(value);
}

export const TypeOrigin = Object.freeze({
  System: "system",
  User: "user",
  Group: "group",
} as const);
export type TypeOrigin = (typeof TypeOrigin)[keyof typeof TypeOrigin];
export const AllTypeOrigins = Object.freeze([TypeOrigin.System, TypeOrigin.User, TypeOrigin.Group] as const satisfies readonly TypeOrigin[]);
export function isTypeOrigin(value: unknown): value is TypeOrigin {
  return typeof value === "string" && (Object.values(TypeOrigin) as readonly string[]).includes(value);
}

export const ValueDomainKind = Object.freeze({
  Enumerated: "enumerated",
  Described: "described",
} as const);
export type ValueDomainKind = (typeof ValueDomainKind)[keyof typeof ValueDomainKind];
export const AllValueDomainKinds = Object.freeze([ValueDomainKind.Enumerated, ValueDomainKind.Described] as const satisfies readonly ValueDomainKind[]);
export function isValueDomainKind(value: unknown): value is ValueDomainKind {
  return typeof value === "string" && (Object.values(ValueDomainKind) as readonly string[]).includes(value);
}

export const Visibility = Object.freeze({
  Private: "private",
  Group: "group",
  Public: "public",
} as const);
export type Visibility = (typeof Visibility)[keyof typeof Visibility];
export const AllVisibilities = Object.freeze([Visibility.Private, Visibility.Group, Visibility.Public] as const satisfies readonly Visibility[]);
export function isVisibility(value: unknown): value is Visibility {
  return typeof value === "string" && (Object.values(Visibility) as readonly string[]).includes(value);
}
