// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { components } from "./internal/generated/types.js";

export const typesVersion = "0.1.0" as const;

export type BestiaryHarness = components["schemas"]["BestiaryHarness"];
export type EntryType = components["schemas"]["EntryType"];
export type ModelID = components["schemas"]["ModelID"];
export type Provider = components["schemas"]["Provider"];
export type QualityMetrics = components["schemas"]["QualityMetrics"];
export type Role = components["schemas"]["Role"];
export type SessionEntry = components["schemas"]["SessionEntry"];
export type SessionID = components["schemas"]["SessionID"];
export type SessionOutcome = components["schemas"]["SessionOutcome"];
export type StopReason = components["schemas"]["StopReason"];
export type ToolCallKind = components["schemas"]["ToolCallKind"];
export type Visibility = components["schemas"]["Visibility"];
