// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { paths as GeneratedPaths, operations as GeneratedOperations } from "./internal/generated/village-api.js";

export const VillageAPIVersion = "0.5.0" as const;

export type paths = GeneratedPaths;
export type operations = GeneratedOperations;
