package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/peasant-labs/schema"

	"gopkg.in/yaml.v3"
)

// redactionsYAMLRelPath is the committed location of the generated redaction
// example corpus, relative to the module root.
var redactionsYAMLRelPath = filepath.Join("testdata", "session-detail", "redactions.yaml")

// redactionsHeader is the DO-NOT-EDIT banner prepended to the generated YAML. It
// documents the no-drift chain so an operator who opens the file is pointed at the
// real source (RedactionExamples) and the gate that enforces it.
const redactionsHeader = `# Code generated by ` + "`go run ./cmd/schema-gen`" + `. DO NOT EDIT.
#
# Source of truth: RedactionExamples in redactions.go (schema repo root).
# This file is a FORMAT-ONLY serialisation of that typed slice — the generator
# never recomputes redactedReplacement. The redaction ENGINE lives only in
# peasant (pkg/redact); a peasant-side behavioural conformance test
# (pkg/redact/redactconform_test.go) runs the real engine over each originalText
# and asserts the output equals the stored redactedReplacement (the no-drift
# guarantee). The web mock (web/src/lib/session-detail/mock-redactions.ts) is in
# turn GENERATED from this file. To change a case: edit RedactionExamples, run
# ` + "`go run ./cmd/schema-gen`" + `, and commit. The leaf freshness gate fails on a
# hand-edited committed copy.
#
# Values are non-functional example/test data (no real credentials). GitHub push
# protection may flag some by pattern — that is cautionary only and is approved
# interactively at push time; the realistic formats are retained on purpose so the
# fixture exemplifies what the redactor actually detects.

`

// buildRedactionsYAML serialises schema.RedactionExamples into the committed
// redactions.yaml byte form: the DO-NOT-EDIT header followed by a single
// top-level `redactions:` list. It is the ONE function both main() and the
// freshness test call, so the committed file and the gate can never disagree on
// formatting. It SERIALISES ONLY — it never invokes the redaction engine.
func buildRedactionsYAML() ([]byte, error) {
	doc := struct {
		Redactions []schema.RedactionExample `yaml:"redactions"`
	}{Redactions: schema.RedactionExamples}

	var body bytes.Buffer
	enc := yaml.NewEncoder(&body)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("marshal redaction examples to YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close YAML encoder: %w", err)
	}

	out := make([]byte, 0, len(redactionsHeader)+body.Len())
	out = append(out, redactionsHeader...)
	out = append(out, body.Bytes()...)
	return out, nil
}

// generateRedactions writes the serialised corpus to its committed path under
// moduleRoot. Wired into main() so a single `go run ./cmd/schema-gen` regenerates
// ALL artifacts (OpenAPI specs + this fixture).
func generateRedactions(moduleRoot string) error {
	data, err := buildRedactionsYAML()
	if err != nil {
		return err
	}
	path := filepath.Join(moduleRoot, redactionsYAMLRelPath)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
