package main

import (
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	schema "github.com/peasant-labs/schema"
)

func TestTypeScriptCatalogCompletenessAndCollisions(t *testing.T) {
	root, err := findModuleRoot()
	if err != nil {
		t.Fatalf("find module root: %v", err)
	}
	specs := []struct {
		surface string
		path    string
	}{
		{"types", filepath.Join(root, "generated", "types-"+schema.TypesVersion+".json")},
		{"local", filepath.Join(root, "generated", "peasantlocal-api-"+schema.PeasantLocalAPIVersion+".json")},
		{"village", filepath.Join(root, "generated", "village-api-"+schema.VillageAPIVersion+".json")},
	}
	var aliases []schemaAlias
	for _, spec := range specs {
		got, err := loadSchemaAliases(spec.surface, spec.path)
		if err != nil {
			t.Fatalf("load %s aliases: %v", spec.surface, err)
		}
		aliases = append(aliases, got...)
	}
	if len(aliases) != 119 {
		t.Fatalf("raw component occurrence count = %d, want 119", len(aliases))
	}
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		t.Fatalf("deduplicate current aliases: %v", err)
	}
	if len(unique) != 97 {
		t.Fatalf("named root export count = %d, want 97", len(unique))
	}
}

func TestTypeScriptCollisionFailsClosedOnUnequalSchemas(t *testing.T) {
	canonical := []byte(`{"type":"string"}`)
	aliases := []schemaAlias{
		{Name: "Example", RawName: "SchemaExample", Surface: "village", Canonical: canonical},
		{Name: "Example", RawName: "Example", Surface: "types", Canonical: []byte(`{"type":"integer"}`)},
	}
	_, err := deduplicateAliases(aliases)
	if err == nil {
		t.Fatal("deduplicateAliases accepted unequal schemas with the same normalized name")
	}
	if !strings.Contains(err.Error(), "Example") || !strings.Contains(err.Error(), "unequal canonical schemas") {
		t.Fatalf("collision error is not actionable: %v", err)
	}
}

func TestGeneratedTypeScriptFilesFullyAccounted(t *testing.T) {
	root, err := findModuleRoot()
	if err != nil {
		t.Fatalf("find module root: %v", err)
	}
	sourceRoot := filepath.Join(root, "typescript", "src")
	expected := []string{
		"fixtures/quality.ts",
		"index.ts",
		"internal/generated/local-api.ts",
		"internal/generated/types.ts",
		"internal/generated/village-api.ts",
		"local-api.ts",
		"types.ts",
		"village-api.ts",
	}
	var actual []string
	err = filepath.WalkDir(sourceRoot, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".ts" {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.HasPrefix(data, []byte(generatedTypeScriptHead)) || bytes.HasPrefix(data, []byte("/**\n * This file was auto-generated by openapi-typescript.")) {
			relative, err := filepath.Rel(sourceRoot, path)
			if err != nil {
				return err
			}
			actual = append(actual, filepath.ToSlash(relative))
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk TypeScript sources: %v", err)
	}
	sort.Strings(expected)
	sort.Strings(actual)
	if strings.Join(actual, "\n") != strings.Join(expected, "\n") {
		t.Fatalf("generated TypeScript files are not fully accounted\nactual:\n%s\nexpected:\n%s", strings.Join(actual, "\n"), strings.Join(expected, "\n"))
	}
}

func TestRenderQualityFixturesDeterministicAndComplete(t *testing.T) {
	fixtures, err := loadQualityFixturesForGenerator()
	if err != nil {
		t.Fatal(err)
	}
	first, err := renderQualityFixtures(fixtures)
	if err != nil {
		t.Fatalf("first render: %v", err)
	}
	second, err := renderQualityFixtures(fixtures)
	if err != nil {
		t.Fatalf("second render: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("quality TypeScript rendering is nondeterministic")
	}
	for _, needle := range []string{"resolved_typical", "resolved_minimal", "project_mix", "tokenRatios", "specQualityScore"} {
		if !bytes.Contains(first, []byte(needle)) {
			t.Errorf("quality TypeScript output missing %q", needle)
		}
	}
}

func loadQualityFixturesForGenerator() (*schema.QualityFixtures, error) {
	return schema.LoadQualityFixtures()
}
