package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"

	schema "github.com/peasant-labs/schema"
	"github.com/peasant-labs/schema/testcase"
)

const (
	openAPITypescriptVersion = "7.13.0"
	generatedTypeScriptHead  = "// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.\n"
)

type typeScriptSurface struct {
	name       string
	version    string
	spec       string
	rawOutput  string
	publicFile string
	versionVar string
}

type schemaAlias struct {
	Name      string
	RawName   string
	Surface   string
	Canonical []byte
}

func generateTypeScript(moduleRoot string) error {
	packageRoot := filepath.Join(moduleRoot, "typescript")
	surfaces := typeScriptSurfaces(moduleRoot, packageRoot)

	tool, err := openAPITypescriptBinary(packageRoot)
	if err != nil {
		return err
	}
	for _, surface := range surfaces {
		if err := os.MkdirAll(filepath.Dir(surface.rawOutput), 0o755); err != nil {
			return fmt.Errorf("create TypeScript generated directory for %s: %w", surface.name, err)
		}
		cmd := exec.Command(tool, surface.spec, "--output", surface.rawOutput, "--export-type")
		cmd.Dir = packageRoot
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("generate %s TypeScript bindings from %s with openapi-typescript %s: %w\n%s", surface.name, surface.spec, openAPITypescriptVersion, err, output)
		}
	}

	aliasesBySurface := make(map[string][]schemaAlias, len(surfaces))
	for _, surface := range surfaces {
		aliases, err := loadSchemaAliases(surface.name, surface.spec)
		if err != nil {
			return err
		}
		aliasesBySurface[surface.name] = aliases
	}
	typesAliases := aliasesBySurface["types"]
	if err := canonicalizeRootProjectHashIdentity(surfaces[0].rawOutput); err != nil {
		return err
	}
	for _, surface := range surfaces {
		if surface.name != "types" {
			if err := canonicalizeAPIOperationReferences(surface, aliasesBySurface[surface.name], typesAliases); err != nil {
				return err
			}
		}
		aliases := aliasesBySurface[surface.name]
		facade, err := renderSurfaceFacade(surface, aliases)
		if err != nil {
			return err
		}
		if err := writeGeneratedFile(surface.publicFile, facade); err != nil {
			return err
		}
	}

	root, err := renderRootFacade(typesAliases)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "index.ts"), root); err != nil {
		return err
	}

	testcaseModel, err := renderTestcaseModel()
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "internal", "generated", "testcase.ts"), testcaseModel); err != nil {
		return err
	}

	fixtures, err := schema.LoadQualityFixtures()
	if err != nil {
		return fmt.Errorf("generate TypeScript quality fixtures: canonical Go loader rejected testdata/quality/sessions.yaml: %w", err)
	}
	quality, err := renderQualityFixtures(fixtures)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "fixtures", "quality.ts"), quality); err != nil {
		return err
	}

	timelineFixtures, err := schema.LoadTimelineFixtures()
	if err != nil {
		return fmt.Errorf("generate TypeScript timeline fixtures: canonical Go loader rejected testdata/local-api/timeline.yaml: %w", err)
	}
	timeline, err := renderTimelineFixtures(timelineFixtures)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "fixtures", "timeline.ts"), timeline); err != nil {
		return err
	}

	return nil
}

var projectHashPropertyPattern = regexp.MustCompile(`(?m)^(\s+(?:projectHash|targetProjectHash)(?:\?)?: )([^;\n]*\bstring\b[^;\n]*);$`)

// canonicalizeRootProjectHashIdentity refines the structural OpenAPI output
// after generation. OpenAPI can describe the ProjectHash constraints, but it
// cannot express TypeScript nominal identity. Keeping the private brand in the
// raw catalog makes every public payload that references ProjectHash carry the
// same identity while the package root remains the sole domain namespace.
func canonicalizeRootProjectHashIdentity(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated root TypeScript catalog for ProjectHash canonicalization: %w", err)
	}
	source := string(data)
	headerEnd := " */\n\n"
	if !strings.Contains(source, headerEnd) {
		return fmt.Errorf("generated root TypeScript catalog at %s has an unrecognized openapi-typescript header; cannot attach the ProjectHash nominal identity", path)
	}
	brand := "declare const projectHashBrand: unique symbol;\ntype CanonicalProjectHash = string & { readonly [projectHashBrand]: \"ProjectHash\" };\n\n"
	source = strings.Replace(source, headerEnd, headerEnd+brand, 1)
	const component = "        ProjectHash: string;"
	if count := strings.Count(source, component); count != 1 {
		return fmt.Errorf("generated root TypeScript catalog at %s contains %d plain ProjectHash component declarations, want exactly 1 before nominal canonicalization; inspect the generated Types schema before publishing", path, count)
	}
	source = strings.Replace(source, component, "        ProjectHash: CanonicalProjectHash;", 1)
	source = rewriteProjectHashProperties(source, `components["schemas"]["ProjectHash"]`)
	if projectHashPropertyPattern.MatchString(source) {
		return fmt.Errorf("generated root TypeScript catalog at %s still contains an unbranded projectHash or targetProjectHash property after nominal canonicalization; add the new openapi-typescript shape to rewriteProjectHashProperties before publishing", path)
	}
	return writeGeneratedFile(path, []byte(source))
}

func rewriteProjectHashProperties(source, replacement string) string {
	return projectHashPropertyPattern.ReplaceAllStringFunc(source, func(line string) string {
		return strings.Replace(line, "string", replacement, 1)
	})
}

func typeScriptSurfaces(moduleRoot, packageRoot string) []typeScriptSurface {
	return []typeScriptSurface{
		{
			name:       "types",
			version:    schema.TypesVersion,
			spec:       filepath.Join(moduleRoot, "generated", "types-"+schema.TypesVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "types.ts"),
			publicFile: filepath.Join(packageRoot, "src", "types.ts"),
			versionVar: "TypesVersion",
		},
		{
			name:       "local",
			version:    schema.PeasantLocalAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "peasantlocal-api-"+schema.PeasantLocalAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "local-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "local-api.ts"),
			versionVar: "PeasantLocalAPIVersion",
		},
		{
			name:       "village",
			version:    schema.VillageAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "village-api-"+schema.VillageAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "village-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "village-api.ts"),
			versionVar: "VillageAPIVersion",
		},
	}
}

// typeScriptGeneratedFiles returns every source file owned by TypeScript
// generation. Keeping this inventory beside the production surface descriptors
// makes freshness and accounting tests follow the generator automatically.
func typeScriptGeneratedFiles(moduleRoot, packageRoot string) []string {
	files := []string{
		filepath.Join(packageRoot, "src", "index.ts"),
		filepath.Join(packageRoot, "src", "internal", "generated", "testcase.ts"),
		filepath.Join(packageRoot, "src", "fixtures", "quality.ts"),
		filepath.Join(packageRoot, "src", "fixtures", "timeline.ts"),
	}
	for _, surface := range typeScriptSurfaces(moduleRoot, packageRoot) {
		files = append(files, surface.rawOutput, surface.publicFile)
	}
	return files
}

func openAPITypescriptBinary(packageRoot string) (string, error) {
	metadataPath := filepath.Join(packageRoot, "node_modules", "openapi-typescript", "package.json")
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s at %s: %w; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` from the module root", openAPITypescriptVersion, metadataPath, err)
	}
	var metadata struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(data, &metadata); err != nil {
		return "", fmt.Errorf("read openapi-typescript version from %s: %w", metadataPath, err)
	}
	if metadata.Version != openAPITypescriptVersion {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s, found %s at %s; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` to restore the lockfile", openAPITypescriptVersion, metadata.Version, metadataPath)
	}
	binary := filepath.Join(packageRoot, "node_modules", ".bin", "openapi-typescript")
	if _, err := os.Stat(binary); err != nil {
		return "", fmt.Errorf("TypeScript generation cannot find %s: %w; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` from the module root", binary, err)
	}
	return binary, nil
}

func loadSchemaAliases(surface, specPath string) ([]schemaAlias, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, fmt.Errorf("read %s schema catalog %s: %w", surface, specPath, err)
	}
	var spec struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("decode %s schema catalog %s: %w", surface, specPath, err)
	}
	if len(spec.Components.Schemas) == 0 {
		return nil, fmt.Errorf("%s schema catalog %s has no components.schemas; named TypeScript exports cannot be generated", surface, specPath)
	}

	aliases := make([]schemaAlias, 0, len(spec.Components.Schemas))
	for rawName, rawSchema := range spec.Components.Schemas {
		name := canonicalTypeScriptName(surface, rawName)
		if name == "" {
			return nil, fmt.Errorf("%s schema %q normalizes to an empty TypeScript name", surface, rawName)
		}
		canonical, err := canonicalSchema(surface, rawSchema)
		if err != nil {
			return nil, fmt.Errorf("canonicalize %s schema %q: %w", surface, rawName, err)
		}
		aliases = append(aliases, schemaAlias{Name: name, RawName: rawName, Surface: surface, Canonical: canonical})
	}
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].Name == aliases[j].Name {
			return aliases[i].RawName < aliases[j].RawName
		}
		return aliases[i].Name < aliases[j].Name
	})
	return aliases, nil
}

func canonicalTypeScriptName(surface, name string) string {
	if surface != "types" {
		name = strings.TrimPrefix(name, "Schema")
	}
	if name == "BestiaryHarness" || name == "Provider" {
		return "Harness"
	}
	return name
}

func canonicalSchema(surface string, raw json.RawMessage) ([]byte, error) {
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil, err
	}
	normalizeSchemaRefs(surface, value)
	return json.Marshal(value)
}

func normalizeSchemaRefs(surface string, value any) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			if key == "$ref" {
				if ref, ok := child.(string); ok {
					const prefix = "#/components/schemas/"
					if strings.HasPrefix(ref, prefix) {
						value[key] = prefix + canonicalTypeScriptName(surface, strings.TrimPrefix(ref, prefix))
					}
				}
				continue
			}
			normalizeSchemaRefs(surface, child)
		}
	case []any:
		for _, child := range value {
			normalizeSchemaRefs(surface, child)
		}
	}
}

func canonicalizeAPIOperationReferences(surface typeScriptSurface, aliases, rootAliases []schemaAlias) error {
	rootByName := make(map[string]schemaAlias, len(rootAliases))
	for _, alias := range rootAliases {
		if prior, duplicate := rootByName[alias.Name]; duplicate {
			if !bytes.Equal(prior.Canonical, alias.Canonical) {
				return fmt.Errorf("canonicalize %s operation references: canonical root type %q has unequal component definitions %q and %q; generation cannot choose a trustworthy public identity; remove the duplicate or make the schemas exactly equal", surface.name, alias.Name, prior.RawName, alias.RawName)
			}
			continue
		}
		rootByName[alias.Name] = alias
	}
	for _, alias := range aliases {
		rootName := canonicalTypeScriptName(surface.name, alias.RawName)
		root, exists := rootByName[rootName]
		if !exists {
			continue
		}
		if !bytes.Equal(alias.Canonical, root.Canonical) {
			return fmt.Errorf("canonicalize %s operation references: API component %q normalizes to canonical root type %q but its schema is unequal during TypeScript generation; rewriting it would misrepresent the HTTP contract; rename an operation-specific body or make the component exactly equal to root component %q", surface.name, alias.RawName, rootName, root.RawName)
		}
	}
	data, err := os.ReadFile(surface.rawOutput)
	if err != nil {
		return fmt.Errorf("read generated %s operation types: %w", surface.name, err)
	}
	source := string(data)
	headerEnd := " */\n\n"
	if !strings.Contains(source, headerEnd) {
		return fmt.Errorf("generated %s operation types at %s have an unrecognized openapi-typescript header; cannot attach canonical root imports", surface.name, surface.rawOutput)
	}
	source = strings.Replace(source, headerEnd, headerEnd+"import type * as Schema from \"../../index.js\";\n\n", 1)
	for _, alias := range aliases {
		rootName := canonicalTypeScriptName(surface.name, alias.RawName)
		if _, exists := rootByName[rootName]; !exists {
			continue
		}
		from := fmt.Sprintf("components[\"schemas\"][%q]", alias.RawName)
		to := "Schema." + rootName
		source = strings.ReplaceAll(source, from, to)
	}
	// swaggest emits some constrained fields and path scalars inline. Restore
	// the branded root identity only after every same-named component above has
	// passed the exact schema-equality gate.
	source = rewriteProjectHashProperties(source, "Schema.ProjectHash")
	if projectHashPropertyPattern.MatchString(source) {
		return fmt.Errorf("generated %s operation types at %s still contain an unbranded projectHash or targetProjectHash property after canonicalization; add the new openapi-typescript shape to rewriteProjectHashProperties before publishing", surface.name, surface.rawOutput)
	}
	if strings.Contains(source, "export type ") && strings.Contains(source, "components[\"schemas\"][\"SchemaProjectResolutionPayload\"]") {
		return fmt.Errorf("generated %s operation types still reference a duplicate ProjectResolutionPayload dialect; map the operation to the canonical root type", surface.name)
	}
	return writeGeneratedFile(surface.rawOutput, []byte(source))
}

func renderSurfaceFacade(surface typeScriptSurface, _ []schemaAlias) ([]byte, error) {
	if surface.name == "types" {
		return []byte(generatedTypeScriptHead + "/** @deprecated Import canonical domain types from the package root. */\nexport * from \"./index.js\";\n"), nil
	}
	var generatedModule string
	if surface.name == "local" {
		generatedModule = "local-api"
	} else {
		generatedModule = "village-api"
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	fmt.Fprintf(&out, "import type { paths as GeneratedPaths, operations as GeneratedOperations } from \"./internal/generated/%s.js\";\n\n", generatedModule)
	fmt.Fprintf(&out, "export const %s = %q as const;\n\n", surface.versionVar, surface.version)
	out.WriteString("export type paths = GeneratedPaths;\n")
	out.WriteString("export type operations = GeneratedOperations;\n")
	return []byte(out.String()), nil
}

func renderRootFacade(aliases []schemaAlias) ([]byte, error) {
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		return nil, fmt.Errorf("generate root named TypeScript exports: %w", err)
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { components as TypesComponents } from \"./internal/generated/types.js\";\n")
	out.WriteString("\n")
	fmt.Fprintf(&out, "export const VillageAPIVersion = %q as const;\n", schema.VillageAPIVersion)
	fmt.Fprintf(&out, "export const PeasantLocalAPIVersion = %q as const;\n", schema.PeasantLocalAPIVersion)
	fmt.Fprintf(&out, "export const TypesVersion = %q as const;\n\n", schema.TypesVersion)
	enums, err := typeScriptEnums()
	if err != nil {
		return nil, err
	}
	enumNames := enumNameSet(enums)
	for _, alias := range unique {
		if _, runtimeEnum := enumNames[alias.Name]; runtimeEnum {
			continue
		}
		fmt.Fprintf(&out, "export type %s = TypesComponents[\"schemas\"][%q];\n", alias.Name, alias.RawName)
	}
	renderGoParityExports(&out)
	if err := renderRuntimeEnums(&out, enums); err != nil {
		return nil, err
	}
	return []byte(out.String()), nil
}

func renderGoParityExports(out *strings.Builder) {
	out.WriteString("\nexport type PushContractVersion = ContractVersion;\n")
	fmt.Fprintf(out, "export const MetadataSchemaVersion = %d as const;\n", schema.MetadataSchemaVersion)
	out.WriteString(`
const projectHashPattern = /^[0-9a-f]{64}$/;

function assertProjectHash(value: unknown, operation: "newProjectHash" | "validateProjectHash"): asserts value is ProjectHash {
  if (!isProjectHash(value)) {
    let rendered: string;
    try {
      rendered = JSON.stringify(value) ?? String(value);
    } catch {
      rendered = String(value);
    }
    throw new TypeError("ProjectHash validation failed for " + rendered + " at @peasant-labs/schema ProjectHash during " + operation + ": the value is not a 64-character lowercase hexadecimal string; callers cannot use it as a canonical project identity; pass the lowercase SHA-256 hex digest of the project origin URL or local path.");
  }
}

export function isProjectHash(value: unknown): value is ProjectHash {
  return typeof value === "string" && projectHashPattern.test(value);
}

export function validateProjectHash(value: unknown): asserts value is ProjectHash {
  assertProjectHash(value, "validateProjectHash");
}

export function newProjectHash(raw: string): ProjectHash {
  assertProjectHash(raw, "newProjectHash");
  return raw;
}
`)
}

func enumNameSet(enums []typeScriptEnum) map[string]struct{} {
	out := make(map[string]struct{}, len(enums))
	for _, enum := range enums {
		out[enum.Name] = struct{}{}
	}
	return out
}

func renderRuntimeEnums(out *strings.Builder, enums []typeScriptEnum) error {
	for _, enum := range enums {
		out.WriteString("\nexport const ")
		out.WriteString(enum.Name)
		out.WriteString(" = Object.freeze({\n")
		byValue := make(map[string]string, len(enum.Members))
		for _, member := range enum.Members {
			encoded, err := json.Marshal(member.Value)
			if err != nil {
				return fmt.Errorf("encode TypeScript enum %s.%s: %w", enum.Name, member.Name, err)
			}
			fmt.Fprintf(out, "  %s: %s,\n", member.Name, encoded)
			byValue[member.Value] = member.Name
		}
		out.WriteString("} as const);\n")
		fmt.Fprintf(out, "export type %s = (typeof %s)[keyof typeof %s];\n", enum.Name, enum.Name, enum.Name)
		fmt.Fprintf(out, "export const %s = Object.freeze([", enum.AllName)
		for i, value := range enum.All {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(out, "%s.%s", enum.Name, byValue[value])
		}
		fmt.Fprintf(out, "] as const satisfies readonly %s[]);\n", enum.Name)
		fmt.Fprintf(out, "export function is%s(value: unknown): value is %s {\n", enum.Name, enum.Name)
		fmt.Fprintf(out, "  return typeof value === \"string\" && (Object.values(%s) as readonly string[]).includes(value);\n", enum.Name)
		out.WriteString("}\n")
	}
	return nil
}

func renderTestcaseModel() ([]byte, error) {
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	writeClosedSet := func(typeName string, values []string) error {
		fmt.Fprintf(&out, "export const %s = Object.freeze({\n", typeName)
		for _, value := range values {
			encoded, err := json.Marshal(value)
			if err != nil {
				return fmt.Errorf("encode testcase %s value %q: %w", typeName, value, err)
			}
			fmt.Fprintf(&out, "  %s: %s,\n", enumMemberName(typeName, value), encoded)
		}
		out.WriteString("} as const);\n")
		fmt.Fprintf(&out, "export type %s = (typeof %s)[keyof typeof %s];\n", typeName, typeName, typeName)
		fmt.Fprintf(&out, "export const All%ss = Object.freeze(Object.values(%s)) as readonly %s[];\n", typeName, typeName, typeName)
		fmt.Fprintf(&out, "export function is%s(value: unknown): value is %s {\n", typeName, typeName)
		fmt.Fprintf(&out, "  return typeof value === \"string\" && (All%ss as readonly string[]).includes(value);\n", typeName)
		out.WriteString("}\n\n")
		return nil
	}
	classifications := make([]string, len(testcase.AllClassifications))
	for index, value := range testcase.AllClassifications {
		classifications[index] = value.String()
	}
	if err := writeClosedSet("Classification", classifications); err != nil {
		return nil, err
	}
	sources := make([]string, len(testcase.AllProvenanceSources))
	for index, value := range testcase.AllProvenanceSources {
		sources[index] = value.String()
	}
	if err := writeClosedSet("ProvenanceSource", sources); err != nil {
		return nil, err
	}

	provenanceType := reflect.TypeFor[testcase.Provenance]()
	mutationType := reflect.TypeFor[testcase.Mutation]()
	caseType := reflect.TypeFor[testcase.Case[any, any]]()
	corpusType := reflect.TypeFor[testcase.Corpus[any, any]]()
	jsonName := func(structType reflect.Type, fieldName string) (string, error) {
		field, ok := structType.FieldByName(fieldName)
		if !ok {
			return "", fmt.Errorf("generate testcase TypeScript model: Go field %s.%s is missing", structType.Name(), fieldName)
		}
		name := strings.Split(field.Tag.Get("json"), ",")[0]
		if name == "" || name == "-" {
			return "", fmt.Errorf("generate testcase TypeScript model: Go field %s.%s has unusable json tag %q", structType.Name(), fieldName, field.Tag.Get("json"))
		}
		return name, nil
	}
	provenanceSource, err := jsonName(provenanceType, "Source")
	if err != nil {
		return nil, err
	}
	provenanceRef, err := jsonName(provenanceType, "Ref")
	if err != nil {
		return nil, err
	}
	mutationDescription, err := jsonName(mutationType, "Description")
	if err != nil {
		return nil, err
	}
	caseFields := make(map[string]string)
	for _, field := range []string{"Name", "Input", "Expected", "Classification", "Provenance", "Mutation"} {
		caseFields[field], err = jsonName(caseType, field)
		if err != nil {
			return nil, err
		}
	}
	corpusCases, err := jsonName(corpusType, "Cases")
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&out, "export interface Provenance {\n  %s: ProvenanceSource;\n  %s: string;\n}\n\n", provenanceSource, provenanceRef)
	fmt.Fprintf(&out, "export interface Mutation {\n  %s: string;\n}\n\n", mutationDescription)
	fmt.Fprintf(&out, "export interface Case<I, E> {\n  %s: string;\n  %s: I;\n  %s: E;\n  %s: Classification;\n  %s: Provenance;\n  %s: Mutation;\n}\n\n", caseFields["Name"], caseFields["Input"], caseFields["Expected"], caseFields["Classification"], caseFields["Provenance"], caseFields["Mutation"])
	fmt.Fprintf(&out, "export interface Corpus<I, E> {\n  %s: Case<I, E>[];\n}\n\n", corpusCases)
	out.WriteString("export function checkMin<I, E>(corpus: Corpus<I, E>, minimum: number): Error | undefined {\n")
	out.WriteString("  if (!Number.isSafeInteger(minimum) || minimum < 0) return new Error(`minimum must be a non-negative safe integer, got ${String(minimum)}`);\n")
	out.WriteString("  if (corpus.cases.length < minimum) return new Error(`corpus has ${corpus.cases.length} case(s), want at least ${minimum}`);\n  return undefined;\n}\n\n")
	out.WriteString("export function validateCase<I, E>(testCase: Case<I, E>): Error | undefined {\n")
	out.WriteString("  const path = `case ${JSON.stringify(testCase.name)}`;\n")
	out.WriteString("  if (testCase.name.trim() === \"\") return new Error(`${path}: name is empty`);\n")
	out.WriteString("  if (!isClassification(testCase.classification)) return new Error(`${path}: classification ${JSON.stringify(testCase.classification)} is not one of ${AllClassifications.join(\"/\")}`);\n")
	out.WriteString("  if (!isProvenanceSource(testCase.provenance.source)) return new Error(`${path}: provenance source ${JSON.stringify(testCase.provenance.source)} is not a known source`);\n")
	out.WriteString("  if (testCase.provenance.ref.trim() === \"\") return new Error(`${path}: provenance ref is empty (a case must cite why it exists)`);\n")
	out.WriteString("  if (testCase.mutation.description.trim() === \"\") return new Error(`${path}: mutation description is empty (a case must describe the change under test)`);\n  return undefined;\n}\n\n")
	out.WriteString("export function validateCorpus<I, E>(corpus: Corpus<I, E>): Error | undefined {\n  const names = new Set<string>();\n")
	out.WriteString("  for (const [index, testCase] of corpus.cases.entries()) {\n    if (names.has(testCase.name)) return new Error(`corpus case ${index}: duplicate case name ${JSON.stringify(testCase.name)}`);\n    names.add(testCase.name);\n    const error = validateCase(testCase);\n    if (error !== undefined) return new Error(`corpus case ${index}: ${error.message}`, { cause: error });\n  }\n  return undefined;\n}\n")
	return []byte(out.String()), nil
}

func deduplicateAliases(aliases []schemaAlias) ([]schemaAlias, error) {
	byName := make(map[string]schemaAlias, len(aliases))
	for _, alias := range aliases {
		prior, exists := byName[alias.Name]
		if !exists {
			byName[alias.Name] = alias
			continue
		}
		if !bytes.Equal(prior.Canonical, alias.Canonical) {
			return nil, fmt.Errorf("normalized TypeScript name collision for %q: %s.%s and %s.%s have unequal canonical schemas; rename the Go/OpenAPI source rather than choosing one silently", alias.Name, prior.Surface, prior.RawName, alias.Surface, alias.RawName)
		}
	}
	unique := make([]schemaAlias, 0, len(byName))
	for _, alias := range byName {
		unique = append(unique, alias)
	}
	sort.Slice(unique, func(i, j int) bool { return unique[i].Name < unique[j].Name })
	return unique, nil
}

func renderQualityFixtures(fixtures *schema.QualityFixtures) ([]byte, error) {
	payload, err := json.MarshalIndent(fixtures, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal quality fixtures for TypeScript: %w", err)
	}

	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { QualitySession } from \"../index.js\";\n\n")

	writeClosedSet := func(typeName string, values []string) {
		fmt.Fprintf(&out, "export const %s = Object.freeze({\n", typeName)
		for _, value := range values {
			fmt.Fprintf(&out, "  %s: %q,\n", enumMemberName(typeName, value), value)
		}
		out.WriteString("} as const);\n")
		fmt.Fprintf(&out, "export type %s = (typeof %s)[keyof typeof %s];\n", typeName, typeName, typeName)
		fmt.Fprintf(&out, "export const All%ss = Object.freeze(Object.values(%s)) as readonly %s[];\n\n", strings.TrimSuffix(typeName, "Name")+"Name", typeName, typeName)
	}
	sessionNames := make([]string, len(fixtures.Sessions))
	for i, fixture := range fixtures.Sessions {
		sessionNames[i] = string(fixture.Name)
	}
	setNames := make([]string, len(fixtures.Sets))
	for i, fixture := range fixtures.Sets {
		setNames[i] = string(fixture.Name)
	}
	writeClosedSet("QualityFixtureName", sessionNames)
	writeClosedSet("QualityFixtureSetName", setNames)

	for _, fixtureType := range []reflect.Type{
		reflect.TypeFor[schema.QualityStringVariation](), reflect.TypeFor[schema.QualityRatioVariation](),
		reflect.TypeFor[schema.QualityMetricVariation](), reflect.TypeFor[schema.QualityMetricVariations](),
		reflect.TypeFor[schema.QualityVariations](), reflect.TypeFor[schema.QualitySessionFixture](),
		reflect.TypeFor[schema.QualityFixtureSet](), reflect.TypeFor[schema.QualityFixtures](),
	} {
		if err := renderTypeScriptInterface(&out, fixtureType); err != nil {
			return nil, err
		}
	}

	out.WriteString("const canonicalQualityFixtures: QualityFixtures = ")
	out.Write(payload)
	out.WriteString(";\n\n")
	out.WriteString("export function loadQualityFixtures(): QualityFixtures { return structuredClone(canonicalQualityFixtures); }\n\n")
	out.WriteString("export function sessionByName(fixtures: QualityFixtures, name: QualityFixtureName): QualitySessionFixture | undefined {\n")
	out.WriteString("  const fixture = fixtures.sessions.find((candidate) => candidate.name === name);\n  return fixture === undefined ? undefined : structuredClone(fixture);\n}\n\n")
	out.WriteString("export function setByName(fixtures: QualityFixtures, name: QualityFixtureSetName): QualityFixtureSet | undefined {\n")
	out.WriteString("  const fixture = fixtures.sets.find((candidate) => candidate.name === name);\n  return fixture === undefined ? undefined : structuredClone(fixture);\n}\n\n")
	out.WriteString("export function toQualitySession(fixture: QualitySessionFixture): QualitySession {\n  const { name: _name, ...session } = fixture;\n  return structuredClone(session);\n}\n\n")
	out.WriteString("export function qualitySessions(fixtures: QualityFixtures): QualitySession[] { return fixtures.sessions.map(toQualitySession); }\n\n")
	out.WriteString("export function qualitySessionsForSet(fixtures: QualityFixtures, name: QualityFixtureSetName): QualitySession[] {\n")
	out.WriteString("  const fixtureSet = setByName(fixtures, name);\n  if (fixtureSet === undefined) throw new Error(`unknown quality fixture set ${JSON.stringify(name)}`);\n")
	out.WriteString("  return fixtureSet.cases.map((caseName) => {\n    const fixture = sessionByName(fixtures, caseName);\n    if (fixture === undefined) throw new Error(`quality fixture set ${JSON.stringify(name)} references unknown case ${JSON.stringify(caseName)}`);\n    return toQualitySession(fixture);\n  });\n}\n")
	return []byte(out.String()), nil
}

func renderTimelineFixtures(fixtures schema.TimelineFixtureCorpus) ([]byte, error) {
	payload, err := json.MarshalIndent(fixtures, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal timeline fixtures for TypeScript: %w", err)
	}

	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { CommitRef, SessionID, TimelineSessionRef } from \"../index.js\";\n")
	out.WriteString("import type { Case } from \"../testcase.js\";\n\n")
	out.WriteString("export type TimelineFixtureSessionInput = Omit<TimelineSessionRef, \"harness\"> & { harness: string };\n")
	out.WriteString("export type TimelineFixtureCommitInput = Omit<CommitRef, \"sessionIds\"> & { sessionIds: SessionID[] | null };\n\n")
	out.WriteString("export interface TimelineFixtureInput {\n  sessions: TimelineFixtureSessionInput[];\n  commits: TimelineFixtureCommitInput[];\n}\n\n")
	out.WriteString("export interface TimelineFixtureExpected {\n  errorContains?: string;\n}\n\n")
	out.WriteString("export type TimelineFixtureCase = Case<TimelineFixtureInput, TimelineFixtureExpected> & { family: string };\n")
	out.WriteString("export interface TimelineFixtureCorpus { cases: TimelineFixtureCase[]; }\n\n")
	out.WriteString("const canonicalTimelineFixtures: TimelineFixtureCorpus = ")
	out.Write(payload)
	out.WriteString(";\n\n")
	out.WriteString("export function loadTimelineFixtures(): TimelineFixtureCorpus { return structuredClone(canonicalTimelineFixtures); }\n")
	return []byte(out.String()), nil
}

func renderTypeScriptInterface(out *strings.Builder, fixtureType reflect.Type) error {
	fmt.Fprintf(out, "export interface %s {\n", fixtureType.Name())
	for i := 0; i < fixtureType.NumField(); i++ {
		field := fixtureType.Field(i)
		name := strings.Split(field.Tag.Get("json"), ",")[0]
		if name == "" {
			name = strings.Split(field.Tag.Get("yaml"), ",")[0]
		}
		typeName, err := typeScriptFixtureType(field.Type)
		if err != nil {
			return fmt.Errorf("render TypeScript fixture field %s.%s: %w", fixtureType.Name(), field.Name, err)
		}
		fmt.Fprintf(out, "  %s: %s;\n", name, typeName)
	}
	out.WriteString("}\n\n")
	return nil
}

func typeScriptFixtureType(goType reflect.Type) (string, error) {
	if goType.Name() != "" {
		switch goType.Kind() {
		case reflect.String:
			if strings.HasPrefix(goType.Name(), "QualityFixture") {
				return goType.Name(), nil
			}
			return "string", nil
		case reflect.Struct:
			return goType.Name(), nil
		}
	}
	switch goType.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Int, reflect.Int64, reflect.Float64:
		return "number", nil
	case reflect.Slice:
		element, err := typeScriptFixtureType(goType.Elem())
		if err != nil {
			return "", err
		}
		return element + "[]", nil
	case reflect.Struct:
		return goType.Name(), nil
	default:
		return "", fmt.Errorf("unsupported Go kind %s", goType)
	}
}

func writeGeneratedFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create generated TypeScript directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write generated TypeScript artifact %s: %w", path, err)
	}
	return nil
}
