package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	schema "github.com/peasant-labs/schema"
)

const (
	openAPITypescriptVersion = "7.13.0"
	generatedTypeScriptHead  = "// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.\n"
)

type typeScriptSurface struct {
	name       string
	version    string
	spec       string
	rawOutput  string
	publicFile string
	versionVar string
}

type schemaAlias struct {
	Name      string
	RawName   string
	Surface   string
	Canonical []byte
}

func generateTypeScript(moduleRoot string) error {
	packageRoot := filepath.Join(moduleRoot, "typescript")
	surfaces := typeScriptSurfaces(moduleRoot, packageRoot)

	tool, err := openAPITypescriptBinary(packageRoot)
	if err != nil {
		return err
	}
	for _, surface := range surfaces {
		if err := os.MkdirAll(filepath.Dir(surface.rawOutput), 0o755); err != nil {
			return fmt.Errorf("create TypeScript generated directory for %s: %w", surface.name, err)
		}
		cmd := exec.Command(tool, surface.spec, "--output", surface.rawOutput, "--export-type")
		cmd.Dir = packageRoot
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("generate %s TypeScript bindings from %s with openapi-typescript %s: %w\n%s", surface.name, surface.spec, openAPITypescriptVersion, err, output)
		}
	}

	var typesAliases []schemaAlias
	for _, surface := range surfaces {
		aliases, err := loadSchemaAliases(surface.name, surface.spec)
		if err != nil {
			return err
		}
		if surface.name == "types" {
			typesAliases = aliases
		}
		facade, err := renderSurfaceFacade(surface, aliases)
		if err != nil {
			return err
		}
		if err := writeGeneratedFile(surface.publicFile, facade); err != nil {
			return err
		}
	}

	root, err := renderRootFacade(typesAliases)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "index.ts"), root); err != nil {
		return err
	}

	fixtures, err := schema.LoadQualityFixtures()
	if err != nil {
		return fmt.Errorf("generate TypeScript quality fixtures: canonical Go loader rejected testdata/quality/sessions.yaml: %w", err)
	}
	quality, err := renderQualityFixtures(fixtures)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "fixtures", "quality.ts"), quality); err != nil {
		return err
	}

	return nil
}

func typeScriptSurfaces(moduleRoot, packageRoot string) []typeScriptSurface {
	return []typeScriptSurface{
		{
			name:       "types",
			version:    schema.TypesVersion,
			spec:       filepath.Join(moduleRoot, "generated", "types-"+schema.TypesVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "types.ts"),
			publicFile: filepath.Join(packageRoot, "src", "types.ts"),
			versionVar: "TypesVersion",
		},
		{
			name:       "local",
			version:    schema.PeasantLocalAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "peasantlocal-api-"+schema.PeasantLocalAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "local-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "local-api.ts"),
			versionVar: "PeasantLocalAPIVersion",
		},
		{
			name:       "village",
			version:    schema.VillageAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "village-api-"+schema.VillageAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "village-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "village-api.ts"),
			versionVar: "VillageAPIVersion",
		},
	}
}

func openAPITypescriptBinary(packageRoot string) (string, error) {
	metadataPath := filepath.Join(packageRoot, "node_modules", "openapi-typescript", "package.json")
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s at %s: %w; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` from the module root", openAPITypescriptVersion, metadataPath, err)
	}
	var metadata struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(data, &metadata); err != nil {
		return "", fmt.Errorf("read openapi-typescript version from %s: %w", metadataPath, err)
	}
	if metadata.Version != openAPITypescriptVersion {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s, found %s at %s; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` to restore the lockfile", openAPITypescriptVersion, metadata.Version, metadataPath)
	}
	binary := filepath.Join(packageRoot, "node_modules", ".bin", "openapi-typescript")
	if _, err := os.Stat(binary); err != nil {
		return "", fmt.Errorf("TypeScript generation cannot find %s: %w; run `pnpm --dir typescript install --frozen-lockfile --ignore-scripts` from the module root", binary, err)
	}
	return binary, nil
}

func loadSchemaAliases(surface, specPath string) ([]schemaAlias, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, fmt.Errorf("read %s schema catalog %s: %w", surface, specPath, err)
	}
	var spec struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("decode %s schema catalog %s: %w", surface, specPath, err)
	}
	if len(spec.Components.Schemas) == 0 {
		return nil, fmt.Errorf("%s schema catalog %s has no components.schemas; named TypeScript exports cannot be generated", surface, specPath)
	}

	aliases := make([]schemaAlias, 0, len(spec.Components.Schemas))
	for rawName, rawSchema := range spec.Components.Schemas {
		name := canonicalTypeScriptName(surface, rawName)
		if name == "" {
			return nil, fmt.Errorf("%s schema %q normalizes to an empty TypeScript name", surface, rawName)
		}
		canonical, err := canonicalSchema(surface, rawSchema)
		if err != nil {
			return nil, fmt.Errorf("canonicalize %s schema %q: %w", surface, rawName, err)
		}
		aliases = append(aliases, schemaAlias{Name: name, RawName: rawName, Surface: surface, Canonical: canonical})
	}
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].Name == aliases[j].Name {
			return aliases[i].RawName < aliases[j].RawName
		}
		return aliases[i].Name < aliases[j].Name
	})
	return aliases, nil
}

func canonicalTypeScriptName(surface, name string) string {
	if surface != "types" {
		name = strings.TrimPrefix(name, "Schema")
	}
	if name == "BestiaryHarness" || name == "Provider" {
		return "Harness"
	}
	return name
}

func canonicalSchema(surface string, raw json.RawMessage) ([]byte, error) {
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil, err
	}
	normalizeSchemaRefs(surface, value)
	return json.Marshal(value)
}

func normalizeSchemaRefs(surface string, value any) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			if key == "$ref" {
				if ref, ok := child.(string); ok {
					const prefix = "#/components/schemas/"
					if strings.HasPrefix(ref, prefix) {
						value[key] = prefix + canonicalTypeScriptName(surface, strings.TrimPrefix(ref, prefix))
					}
				}
				continue
			}
			normalizeSchemaRefs(surface, child)
		}
	case []any:
		for _, child := range value {
			normalizeSchemaRefs(surface, child)
		}
	}
}

func renderSurfaceFacade(surface typeScriptSurface, aliases []schemaAlias) ([]byte, error) {
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		return nil, fmt.Errorf("generate %s named TypeScript exports: %w", surface.name, err)
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { components } from \"./internal/generated/")
	if surface.name == "local" {
		out.WriteString("local-api")
	} else if surface.name == "village" {
		out.WriteString("village-api")
	} else {
		out.WriteString("types")
	}
	out.WriteString(".js\";\n\n")
	fmt.Fprintf(&out, "export const %s = %q as const;\n\n", surface.versionVar, surface.version)
	enums, err := typeScriptEnums()
	if err != nil {
		return nil, err
	}
	enumNames := enumNameSet(enums)
	for _, alias := range unique {
		if surface.name == "types" {
			if _, runtimeEnum := enumNames[alias.Name]; runtimeEnum {
				continue
			}
		}
		fmt.Fprintf(&out, "export type %s = components[\"schemas\"][%q];\n", alias.Name, alias.RawName)
	}
	if surface.name == "types" {
		if err := renderRuntimeEnums(&out, enums); err != nil {
			return nil, err
		}
	}
	return []byte(out.String()), nil
}

func renderRootFacade(aliases []schemaAlias) ([]byte, error) {
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		return nil, fmt.Errorf("generate root named TypeScript exports: %w", err)
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { components as TypesComponents } from \"./internal/generated/types.js\";\n")
	out.WriteString("\n")
	fmt.Fprintf(&out, "export const VillageAPIVersion = %q as const;\n", schema.VillageAPIVersion)
	fmt.Fprintf(&out, "export const PeasantLocalAPIVersion = %q as const;\n", schema.PeasantLocalAPIVersion)
	fmt.Fprintf(&out, "export const TypesVersion = %q as const;\n\n", schema.TypesVersion)
	enums, err := typeScriptEnums()
	if err != nil {
		return nil, err
	}
	enumNames := enumNameSet(enums)
	for _, alias := range unique {
		if _, runtimeEnum := enumNames[alias.Name]; runtimeEnum {
			continue
		}
		fmt.Fprintf(&out, "export type %s = TypesComponents[\"schemas\"][%q];\n", alias.Name, alias.RawName)
	}
	if err := renderRuntimeEnums(&out, enums); err != nil {
		return nil, err
	}
	return []byte(out.String()), nil
}

func enumNameSet(enums []typeScriptEnum) map[string]struct{} {
	out := make(map[string]struct{}, len(enums))
	for _, enum := range enums {
		out[enum.Name] = struct{}{}
	}
	return out
}

func renderRuntimeEnums(out *strings.Builder, enums []typeScriptEnum) error {
	for _, enum := range enums {
		out.WriteString("\nexport const ")
		out.WriteString(enum.Name)
		out.WriteString(" = Object.freeze({\n")
		byValue := make(map[string]string, len(enum.Members))
		for _, member := range enum.Members {
			encoded, err := json.Marshal(member.Value)
			if err != nil {
				return fmt.Errorf("encode TypeScript enum %s.%s: %w", enum.Name, member.Name, err)
			}
			fmt.Fprintf(out, "  %s: %s,\n", member.Name, encoded)
			byValue[member.Value] = member.Name
		}
		out.WriteString("} as const);\n")
		fmt.Fprintf(out, "export type %s = (typeof %s)[keyof typeof %s];\n", enum.Name, enum.Name, enum.Name)
		fmt.Fprintf(out, "export const %s = Object.freeze([", enum.AllName)
		for i, value := range enum.All {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(out, "%s.%s", enum.Name, byValue[value])
		}
		fmt.Fprintf(out, "] as const satisfies readonly %s[]);\n", enum.Name)
		fmt.Fprintf(out, "export function is%s(value: unknown): value is %s {\n", enum.Name, enum.Name)
		fmt.Fprintf(out, "  return typeof value === \"string\" && (Object.values(%s) as readonly string[]).includes(value);\n", enum.Name)
		out.WriteString("}\n")
	}
	return nil
}

func deduplicateAliases(aliases []schemaAlias) ([]schemaAlias, error) {
	byName := make(map[string]schemaAlias, len(aliases))
	for _, alias := range aliases {
		prior, exists := byName[alias.Name]
		if !exists {
			byName[alias.Name] = alias
			continue
		}
		if !bytes.Equal(prior.Canonical, alias.Canonical) {
			return nil, fmt.Errorf("normalized TypeScript name collision for %q: %s.%s and %s.%s have unequal canonical schemas; rename the Go/OpenAPI source rather than choosing one silently", alias.Name, prior.Surface, prior.RawName, alias.Surface, alias.RawName)
		}
	}
	unique := make([]schemaAlias, 0, len(byName))
	for _, alias := range byName {
		unique = append(unique, alias)
	}
	sort.Slice(unique, func(i, j int) bool { return unique[i].Name < unique[j].Name })
	return unique, nil
}

func renderQualityFixtures(fixtures *schema.QualityFixtures) ([]byte, error) {
	payload, err := json.MarshalIndent(fixtures, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal quality fixtures for TypeScript: %w", err)
	}

	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { QualitySession } from \"../index.js\";\n\n")

	writeClosedSet := func(typeName string, values []string) {
		fmt.Fprintf(&out, "export const %s = Object.freeze({\n", typeName)
		for _, value := range values {
			fmt.Fprintf(&out, "  %s: %q,\n", enumMemberName(typeName, value), value)
		}
		out.WriteString("} as const);\n")
		fmt.Fprintf(&out, "export type %s = (typeof %s)[keyof typeof %s];\n", typeName, typeName, typeName)
		fmt.Fprintf(&out, "export const All%ss = Object.freeze(Object.values(%s)) as readonly %s[];\n\n", strings.TrimSuffix(typeName, "Name")+"Name", typeName, typeName)
	}
	sessionNames := make([]string, len(fixtures.Sessions))
	for i, fixture := range fixtures.Sessions {
		sessionNames[i] = string(fixture.Name)
	}
	setNames := make([]string, len(fixtures.Sets))
	for i, fixture := range fixtures.Sets {
		setNames[i] = string(fixture.Name)
	}
	writeClosedSet("QualityFixtureName", sessionNames)
	writeClosedSet("QualityFixtureSetName", setNames)

	for _, fixtureType := range []reflect.Type{
		reflect.TypeFor[schema.QualityStringVariation](), reflect.TypeFor[schema.QualityRatioVariation](),
		reflect.TypeFor[schema.QualityMetricVariation](), reflect.TypeFor[schema.QualityMetricVariations](),
		reflect.TypeFor[schema.QualityVariations](), reflect.TypeFor[schema.QualitySessionFixture](),
		reflect.TypeFor[schema.QualityFixtureSet](), reflect.TypeFor[schema.QualityFixtures](),
	} {
		if err := renderTypeScriptInterface(&out, fixtureType); err != nil {
			return nil, err
		}
	}

	out.WriteString("const canonicalQualityFixtures: QualityFixtures = ")
	out.Write(payload)
	out.WriteString(";\n\n")
	out.WriteString("export function loadQualityFixtures(): QualityFixtures { return structuredClone(canonicalQualityFixtures); }\n\n")
	out.WriteString("export function sessionByName(fixtures: QualityFixtures, name: QualityFixtureName): QualitySessionFixture | undefined {\n")
	out.WriteString("  const fixture = fixtures.sessions.find((candidate) => candidate.name === name);\n  return fixture === undefined ? undefined : structuredClone(fixture);\n}\n\n")
	out.WriteString("export function setByName(fixtures: QualityFixtures, name: QualityFixtureSetName): QualityFixtureSet | undefined {\n")
	out.WriteString("  const fixture = fixtures.sets.find((candidate) => candidate.name === name);\n  return fixture === undefined ? undefined : structuredClone(fixture);\n}\n\n")
	out.WriteString("export function toQualitySession(fixture: QualitySessionFixture): QualitySession {\n  const { name: _name, ...session } = fixture;\n  return structuredClone(session);\n}\n\n")
	out.WriteString("export function qualitySessions(fixtures: QualityFixtures): QualitySession[] { return fixtures.sessions.map(toQualitySession); }\n\n")
	out.WriteString("export function qualitySessionsForSet(fixtures: QualityFixtures, name: QualityFixtureSetName): QualitySession[] {\n")
	out.WriteString("  const fixtureSet = setByName(fixtures, name);\n  if (fixtureSet === undefined) throw new Error(`unknown quality fixture set ${JSON.stringify(name)}`);\n")
	out.WriteString("  return fixtureSet.cases.map((caseName) => {\n    const fixture = sessionByName(fixtures, caseName);\n    if (fixture === undefined) throw new Error(`quality fixture set ${JSON.stringify(name)} references unknown case ${JSON.stringify(caseName)}`);\n    return toQualitySession(fixture);\n  });\n}\n")
	return []byte(out.String()), nil
}

func renderTypeScriptInterface(out *strings.Builder, fixtureType reflect.Type) error {
	fmt.Fprintf(out, "export interface %s {\n", fixtureType.Name())
	for i := 0; i < fixtureType.NumField(); i++ {
		field := fixtureType.Field(i)
		name := strings.Split(field.Tag.Get("json"), ",")[0]
		if name == "" {
			name = strings.Split(field.Tag.Get("yaml"), ",")[0]
		}
		typeName, err := typeScriptFixtureType(field.Type)
		if err != nil {
			return fmt.Errorf("render TypeScript fixture field %s.%s: %w", fixtureType.Name(), field.Name, err)
		}
		fmt.Fprintf(out, "  %s: %s;\n", name, typeName)
	}
	out.WriteString("}\n\n")
	return nil
}

func typeScriptFixtureType(goType reflect.Type) (string, error) {
	if goType.Name() != "" {
		switch goType.Kind() {
		case reflect.String:
			if strings.HasPrefix(goType.Name(), "QualityFixture") {
				return goType.Name(), nil
			}
			return "string", nil
		case reflect.Struct:
			return goType.Name(), nil
		}
	}
	switch goType.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Int, reflect.Int64, reflect.Float64:
		return "number", nil
	case reflect.Slice:
		element, err := typeScriptFixtureType(goType.Elem())
		if err != nil {
			return "", err
		}
		return element + "[]", nil
	case reflect.Struct:
		return goType.Name(), nil
	default:
		return "", fmt.Errorf("unsupported Go kind %s", goType)
	}
}

func writeGeneratedFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create generated TypeScript directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write generated TypeScript artifact %s: %w", path, err)
	}
	return nil
}
