package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	schema "github.com/peasant-labs/schema"
)

const (
	openAPITypescriptVersion = "7.13.0"
	generatedTypeScriptHead  = "// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.\n"
)

type typeScriptSurface struct {
	name       string
	version    string
	spec       string
	rawOutput  string
	publicFile string
	versionVar string
}

type schemaAlias struct {
	Name      string
	RawName   string
	Surface   string
	Canonical []byte
}

func generateTypeScript(moduleRoot string) error {
	packageRoot := filepath.Join(moduleRoot, "typescript")
	surfaces := []typeScriptSurface{
		{
			name:       "types",
			version:    schema.TypesVersion,
			spec:       filepath.Join(moduleRoot, "generated", "types-"+schema.TypesVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "types.ts"),
			publicFile: filepath.Join(packageRoot, "src", "types.ts"),
			versionVar: "typesVersion",
		},
		{
			name:       "local",
			version:    schema.PeasantLocalAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "peasantlocal-api-"+schema.PeasantLocalAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "local-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "local-api.ts"),
			versionVar: "peasantLocalApiVersion",
		},
		{
			name:       "village",
			version:    schema.VillageAPIVersion,
			spec:       filepath.Join(moduleRoot, "generated", "village-api-"+schema.VillageAPIVersion+".json"),
			rawOutput:  filepath.Join(packageRoot, "src", "internal", "generated", "village-api.ts"),
			publicFile: filepath.Join(packageRoot, "src", "village-api.ts"),
			versionVar: "villageAPIVersion",
		},
	}

	tool, err := openAPITypescriptBinary(packageRoot)
	if err != nil {
		return err
	}
	for _, surface := range surfaces {
		if err := os.MkdirAll(filepath.Dir(surface.rawOutput), 0o755); err != nil {
			return fmt.Errorf("create TypeScript generated directory for %s: %w", surface.name, err)
		}
		cmd := exec.Command(tool, surface.spec, "--output", surface.rawOutput, "--export-type")
		cmd.Dir = packageRoot
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("generate %s TypeScript bindings from %s with openapi-typescript %s: %w\n%s", surface.name, surface.spec, openAPITypescriptVersion, err, output)
		}
	}

	aliasesBySurface := make(map[string][]schemaAlias, len(surfaces))
	var allAliases []schemaAlias
	for _, surface := range surfaces {
		aliases, err := loadSchemaAliases(surface.name, surface.spec)
		if err != nil {
			return err
		}
		aliasesBySurface[surface.name] = aliases
		allAliases = append(allAliases, aliases...)
		facade, err := renderSurfaceFacade(surface, aliases)
		if err != nil {
			return err
		}
		if err := writeGeneratedFile(surface.publicFile, facade); err != nil {
			return err
		}
	}

	root, err := renderRootFacade(allAliases)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "index.ts"), root); err != nil {
		return err
	}

	fixtures, err := schema.LoadQualityFixtures()
	if err != nil {
		return fmt.Errorf("generate TypeScript quality fixtures: canonical Go loader rejected testdata/quality/sessions.yaml: %w", err)
	}
	quality, err := renderQualityFixtures(fixtures)
	if err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(packageRoot, "src", "fixtures", "quality.ts"), quality); err != nil {
		return err
	}

	return nil
}

func openAPITypescriptBinary(packageRoot string) (string, error) {
	metadataPath := filepath.Join(packageRoot, "node_modules", "openapi-typescript", "package.json")
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s at %s: %w; run `npm ci --prefix typescript` from the module root", openAPITypescriptVersion, metadataPath, err)
	}
	var metadata struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(data, &metadata); err != nil {
		return "", fmt.Errorf("read openapi-typescript version from %s: %w", metadataPath, err)
	}
	if metadata.Version != openAPITypescriptVersion {
		return "", fmt.Errorf("TypeScript generation requires openapi-typescript %s, found %s at %s; run `npm ci --prefix typescript` to restore the lockfile", openAPITypescriptVersion, metadata.Version, metadataPath)
	}
	binary := filepath.Join(packageRoot, "node_modules", ".bin", "openapi-typescript")
	if _, err := os.Stat(binary); err != nil {
		return "", fmt.Errorf("TypeScript generation cannot find %s: %w; run `npm ci --prefix typescript` from the module root", binary, err)
	}
	return binary, nil
}

func loadSchemaAliases(surface, specPath string) ([]schemaAlias, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, fmt.Errorf("read %s schema catalog %s: %w", surface, specPath, err)
	}
	var spec struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("decode %s schema catalog %s: %w", surface, specPath, err)
	}
	if len(spec.Components.Schemas) == 0 {
		return nil, fmt.Errorf("%s schema catalog %s has no components.schemas; named TypeScript exports cannot be generated", surface, specPath)
	}

	aliases := make([]schemaAlias, 0, len(spec.Components.Schemas))
	for rawName, rawSchema := range spec.Components.Schemas {
		name := strings.TrimPrefix(rawName, "Schema")
		if name == "" {
			return nil, fmt.Errorf("%s schema %q normalizes to an empty TypeScript name", surface, rawName)
		}
		canonical, err := canonicalSchema(rawSchema)
		if err != nil {
			return nil, fmt.Errorf("canonicalize %s schema %q: %w", surface, rawName, err)
		}
		aliases = append(aliases, schemaAlias{Name: name, RawName: rawName, Surface: surface, Canonical: canonical})
	}
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].Name == aliases[j].Name {
			return aliases[i].RawName < aliases[j].RawName
		}
		return aliases[i].Name < aliases[j].Name
	})
	return aliases, nil
}

func canonicalSchema(raw json.RawMessage) ([]byte, error) {
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil, err
	}
	normalizeSchemaRefs(value)
	return json.Marshal(value)
}

func normalizeSchemaRefs(value any) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			if key == "$ref" {
				if ref, ok := child.(string); ok {
					const prefix = "#/components/schemas/"
					if strings.HasPrefix(ref, prefix) {
						value[key] = prefix + strings.TrimPrefix(strings.TrimPrefix(ref, prefix), "Schema")
					}
				}
				continue
			}
			normalizeSchemaRefs(child)
		}
	case []any:
		for _, child := range value {
			normalizeSchemaRefs(child)
		}
	}
}

func renderSurfaceFacade(surface typeScriptSurface, aliases []schemaAlias) ([]byte, error) {
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		return nil, fmt.Errorf("generate %s named TypeScript exports: %w", surface.name, err)
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { components } from \"./internal/generated/")
	if surface.name == "local" {
		out.WriteString("local-api")
	} else if surface.name == "village" {
		out.WriteString("village-api")
	} else {
		out.WriteString("types")
	}
	out.WriteString(".js\";\n\n")
	fmt.Fprintf(&out, "export const %s = %q as const;\n\n", surface.versionVar, surface.version)
	for _, alias := range unique {
		fmt.Fprintf(&out, "export type %s = components[\"schemas\"][%q];\n", alias.Name, alias.RawName)
	}
	return []byte(out.String()), nil
}

func renderRootFacade(aliases []schemaAlias) ([]byte, error) {
	unique, err := deduplicateAliases(aliases)
	if err != nil {
		return nil, fmt.Errorf("generate root named TypeScript exports: %w", err)
	}
	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { components as TypesComponents } from \"./internal/generated/types.js\";\n")
	out.WriteString("import type { components as LocalComponents } from \"./internal/generated/local-api.js\";\n")
	out.WriteString("import type { components as VillageComponents } from \"./internal/generated/village-api.js\";\n\n")
	componentName := map[string]string{"types": "TypesComponents", "local": "LocalComponents", "village": "VillageComponents"}
	for _, alias := range unique {
		fmt.Fprintf(&out, "export type %s = %s[\"schemas\"][%q];\n", alias.Name, componentName[alias.Surface], alias.RawName)
	}
	return []byte(out.String()), nil
}

func deduplicateAliases(aliases []schemaAlias) ([]schemaAlias, error) {
	byName := make(map[string]schemaAlias, len(aliases))
	for _, alias := range aliases {
		prior, exists := byName[alias.Name]
		if !exists {
			byName[alias.Name] = alias
			continue
		}
		if !bytes.Equal(prior.Canonical, alias.Canonical) {
			return nil, fmt.Errorf("normalized TypeScript name collision for %q: %s.%s and %s.%s have unequal canonical schemas; rename the Go/OpenAPI source rather than choosing one silently", alias.Name, prior.Surface, prior.RawName, alias.Surface, alias.RawName)
		}
	}
	unique := make([]schemaAlias, 0, len(byName))
	for _, alias := range byName {
		unique = append(unique, alias)
	}
	sort.Slice(unique, func(i, j int) bool { return unique[i].Name < unique[j].Name })
	return unique, nil
}

func renderQualityFixtures(fixtures *schema.QualityFixtures) ([]byte, error) {
	sessions, err := json.MarshalIndent(fixtures.Sessions, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal quality session fixtures for TypeScript: %w", err)
	}
	sets, err := json.MarshalIndent(fixtures.Sets, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal quality fixture sets for TypeScript: %w", err)
	}
	variations, err := json.MarshalIndent(fixtures.Variations, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal quality variations for TypeScript: %w", err)
	}

	var out strings.Builder
	out.WriteString(generatedTypeScriptHead)
	out.WriteString("import type { QualitySession } from \"../local-api.js\";\n\n")
	out.WriteString("export const qualitySessions = ")
	out.Write(sessions)
	out.WriteString(" as const satisfies readonly QualitySessionFixture[];\n\n")
	out.WriteString("export const qualityFixtureSets = ")
	out.Write(sets)
	out.WriteString(" as const;\n\n")
	out.WriteString("export const qualityVariations = ")
	out.Write(variations)
	out.WriteString(" as const;\n\n")
	out.WriteString("export type QualityFixtureName = (typeof qualitySessions)[number][\"name\"];\n")
	out.WriteString("export type QualityFixtureSetName = (typeof qualityFixtureSets)[number][\"name\"];\n")
	out.WriteString("export type QualitySessionFixture = QualitySession & { readonly name: string };\n")
	out.WriteString("export type QualityFixtureSet = (typeof qualityFixtureSets)[number];\n\n")
	out.WriteString("export function qualityFixture(name: QualityFixtureName): QualitySessionFixture {\n")
	out.WriteString("  const fixture = qualitySessions.find((candidate) => candidate.name === name);\n")
	out.WriteString("  if (fixture === undefined) throw new Error(`unknown quality fixture ${JSON.stringify(name)}`);\n")
	out.WriteString("  return { ...fixture };\n}\n\n")
	out.WriteString("export function qualityFixtures(names: readonly QualityFixtureName[]): QualitySessionFixture[] {\n")
	out.WriteString("  return names.map(qualityFixture);\n}\n\n")
	out.WriteString("export function qualityFixtureSet(name: QualityFixtureSetName): QualitySessionFixture[] {\n")
	out.WriteString("  const fixtureSet = qualityFixtureSets.find((candidate) => candidate.name === name);\n")
	out.WriteString("  if (fixtureSet === undefined) throw new Error(`unknown quality fixture set ${JSON.stringify(name)}`);\n")
	out.WriteString("  return qualityFixtures(fixtureSet.cases);\n}\n\n")
	out.WriteString("export function allQualityFixtures(): QualitySessionFixture[] {\n")
	out.WriteString("  return qualitySessions.map((fixture) => ({ ...fixture }));\n}\n")
	return []byte(out.String()), nil
}

func writeGeneratedFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create generated TypeScript directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write generated TypeScript artifact %s: %w", path, err)
	}
	return nil
}
