// Package licensecorpus generates the enum-exhaustion test corpus for the closed
// license menu (schema.AllLicenses). It builds one must-pass case per menu member
// plus must-fail negatives, each carrying enum provenance and a non-empty mutation
// description, and renders them as a committed YAML corpus in the schema/testcase
// shape.
//
// The corpus is a GENERATED artifact: cmd/gen-license-corpus writes
// testdata/license_corpus.yaml from BuildCorpus, and two guards keep it honest
// (see the package tests): an exhaustive-coverage test that reddens if the menu
// widens without the corpus regenerated, and a freshness gate that reddens if the
// committed file drifts from a fresh render.
package licensecorpus

import (
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/peasant-labs/schema"
	"github.com/peasant-labs/schema/testcase"
)

//go:generate go run github.com/peasant-labs/schema/cmd/gen-license-corpus

// CommittedCorpusPath is the generated corpus file, relative to this package
// directory (where both go:generate and go test run). cmd/gen-license-corpus
// writes it and the freshness gate reads it back.
const CommittedCorpusPath = "testdata/license_corpus.yaml"

// generatedHeader marks the artifact as generated so it is never hand-edited; the
// freshness gate enforces that.
const generatedHeader = "# Code generated by cmd/gen-license-corpus; DO NOT EDIT.\n" +
	"# Regenerate: go generate ./... (or go run ./cmd/gen-license-corpus).\n" +
	"# Source of truth: schema.AllLicenses (types.go). Widening the menu without\n" +
	"# regenerating this corpus reddens the exhaustive-coverage test.\n"

// licenseNegative is a value outside the closed menu that License.IsValid must
// reject, paired with the mutation that names why rejecting it matters.
type licenseNegative struct {
	name     string
	input    schema.License
	mutation string
}

// negatives are the must-fail cases: a plausible non-menu id and the empty
// license. They are hand-listed (not derived from the enum) because they probe
// values the enum deliberately excludes.
var negatives = []licenseNegative{
	{
		name:     `the non-menu value "MIT" is rejected`,
		input:    schema.License("MIT"),
		mutation: `accepting "MIT" would silently widen the closed license menu beyond AllLicenses.`,
	},
	{
		name:     "the empty license is rejected",
		input:    schema.License(""),
		mutation: "accepting the empty license would admit an unset value the closed menu never lists.",
	},
}

// BuildCorpus enumerates schema.AllLicenses into one must-pass case per member,
// then appends the must-fail negatives. Every case carries Source=SourceEnum, a
// concrete provenance ref, and a non-empty mutation description, so each case
// passes testcase.Case.Validate (never vacuous).
func BuildCorpus() testcase.Corpus[schema.License, bool] {
	cases := make([]testcase.Case[schema.License, bool], 0, len(schema.AllLicenses)+len(negatives))

	for _, l := range schema.AllLicenses {
		cases = append(cases, testcase.Case[schema.License, bool]{
			Name:           "license " + l.String() + " is valid",
			Input:          l,
			Expected:       true,
			Classification: testcase.MustPass,
			Provenance: testcase.Provenance{
				Source: testcase.SourceEnum,
				Ref:    "schema.AllLicenses (types.go)",
			},
			Mutation: testcase.Mutation{
				Description: "removing " + l.String() + " from the AllLicenses menu (or its SQLite CHECK mirror) would reject a license the wire still accepts.",
			},
		})
	}

	for _, neg := range negatives {
		cases = append(cases, testcase.Case[schema.License, bool]{
			Name:           neg.name,
			Input:          neg.input,
			Expected:       false,
			Classification: testcase.MustFail,
			Provenance: testcase.Provenance{
				Source: testcase.SourceEnum,
				Ref:    "schema.License.IsValid (types.go)",
			},
			Mutation: testcase.Mutation{Description: neg.mutation},
		})
	}

	return testcase.Corpus[schema.License, bool]{Cases: cases}
}

// RenderCorpus returns the committed artifact bytes: the generated header followed
// by the YAML encoding of BuildCorpus. It is deterministic, so the freshness gate
// can byte-compare it against the committed file.
func RenderCorpus() ([]byte, error) {
	body, err := yaml.Marshal(BuildCorpus())
	if err != nil {
		return nil, fmt.Errorf("marshal license corpus: %w", err)
	}
	return append([]byte(generatedHeader), body...), nil
}
