// Package openapi builds the committed OpenAPI 3.1 / JSON-Schema artifacts from the
// Go schema source. This schema module is the source of truth; the village vendors +
// serves + enforces these specs (GH #53). Every spec is generated by a Build*Spec
// function and emitted (byte-for-byte) to generated/ at the module root by
// GenerateSpecArtifacts; the codegen-freshness test (cmd/schema-gen) diffs the
// committed copies against a fresh regen and fails on any drift.
//
// # Versioning policy (doc-surface semver)
//
// Each spec carries its OWN info.version, which is an INDEPENDENT doc-surface
// semantic version describing that spec's API SURFACE — not a shared release
// number across specs:
//
//   - Additive change (new route, new schema/component, new enum value) ⇒ MINOR bump.
//   - Breaking change (removed/renamed route or field, changed type, tightened
//     constraint) ⇒ MAJOR bump.
//
// Example: adding the /api/v1/pull surface to the village-api spec was purely
// additive, so VillageAPIVersion went 0.1.0 → 0.2.0 (minor).
//
// This doc-surface semver is a SEPARATE axis from the runtime WIRE-CONTRACT
// versions. The push/pull content contracts are negotiated at runtime via the
// [Min, Current] windows in internal/defaults/schema.go (PushContractVersion /
// PullContractVersion) over GET /api/v1/schema/version. Those windows govern
// whether a given CLI may talk to a given village; the spec's info.version only
// documents the HTTP surface. The two move independently — EXCEPT that an
// envelope-SHAPE change (a breaking change to the publish/pull wire envelope) is
// simultaneously a contract-version bump (it shifts the negotiated window) AND a
// spec major bump (the documented surface changed). A spec-only additive bump does
// NOT touch the contract windows, and a window slide that does not alter the HTTP
// surface does NOT bump the spec.
//
// # Single source per spec
//
// Each spec's version is written in EXACTLY ONE place — the const block in
// artifacts.go (VillageAPIVersion, PeasantLocalAPIVersion, TypesVersion).
// That const feeds, by derivation and never by retyping:
//
//   - info.version, via WithVersion(<Const>) in each Build*Spec function;
//   - the versioned artifact filename (e.g. "village-api-0.2.0.json"), in
//     GenerateSpecArtifacts;
//   - the human-readable doc labels ("Village API v0.2.0") in cmd/schema-gen;
//   - the freshness test's artifact-key assertions.
//
// To cut a new spec version, edit ONLY the relevant const and run
// `go run ./cmd/schema-gen` (NOT `go generate ./...`, which no-ops on this nested
// module). Filenames are versioned; there is no unversioned "latest" alias.
//
// # Publish-body enforcement schema (derived, not separately reflected)
//
// The village ENFORCES incoming publish bodies (422 on schema violation) against a
// standalone PublishRequest JSON Schema it vendors as
// backend/internal/handler/openapispec/publish-request.schema.json. That schema is
// produced by BuildPublishRequestSchema, which EXTRACTS the SchemaPublishRequest
// component — with its full transitive $ref closure, bundled into "$defs" — out of
// the village-api spec itself (JSON Schema 2020-12, the dialect the village's
// santhosh-tekuri validator supports). Deriving the enforced schema FROM the
// documented spec (rather than a separate reflector) means the two can never
// drift. Its filename and "$id" are versioned by VillageAPIVersion, the spec it is
// extracted from.
//
// This REPLACED the retired legacy builders BuildJSONSchema + BuildOpenAPISpec
// (which emitted the push-contract-keyed "openapi-<v>.{json,yaml}" artifacts). The
// retirement is pinned by an enforcement-PARITY gate
// (publish_schema_parity_test.go): a frozen copy of the old BuildJSONSchema output
// (testdata/legacy-publish-request.schema.json) and the new extracted schema must
// return IDENTICAL accept/reject verdicts across a corpus of valid + malformed
// bodies. See GH #53 and unified-schema-1g8jg (option B).
package openapi
