// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { AnnotationPushItem, ProjectHash } from "@peasant-labs/schema";
import type { operations as LocalOperations } from "@peasant-labs/schema/local-api";
import type { operations as VillageOperations } from "@peasant-labs/schema/village-api";

type Same<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
type VillagePublishRequest = NonNullable<VillageOperations["publishTranscript"]["requestBody"]>["content"]["application/json"];
type VillagePullAnnotations = VillageOperations["getPullTranscriptAnnotations"]["responses"][200]["content"]["application/json"];
type VillagePullAnnotation = NonNullable<VillagePullAnnotations>[number];
interface SameSpellingUnconstrained { projectHash: string; targetProjectHash?: string }

const projectHashLocation1: Same<Exclude<AnnotationPushItem["projectHash"], null | undefined>, ProjectHash> = true;
void projectHashLocation1;
const projectHashLocation2: Same<LocalOperations["listReviewChanges"]["parameters"]["path"]["projectHash"], ProjectHash> = true;
void projectHashLocation2;
const projectHashLocation3: Same<LocalOperations["resolveProject"]["responses"][200]["content"]["application/json"]["projectHash"], ProjectHash> = true;
void projectHashLocation3;
const projectHashLocation4: Same<NonNullable<VillagePublishRequest["project"]>["hash"], ProjectHash> = true;
void projectHashLocation4;
const projectHashLocation5: Same<Exclude<VillagePullAnnotation["targetProjectHash"], null | undefined>, ProjectHash> = true;
void projectHashLocation5;
const projectHashLocation6: Same<SameSpellingUnconstrained["projectHash"], string> = true;
void projectHashLocation6;
