// Package enumcorpus generates the enum-exhaustion test corpora for the
// Local API 0.5.0 git+session timeline and insight-first code map closed sets
// (AssociationConclusion, AssociationEvidenceKind, Confidence, RewriteResolution,
// RewriteMethod, InsightKind, InsightProvenance, ReadAttributionState,
// ReadStateGrade) plus a regenerated TargetKind corpus (the file_version
// member added in the same tag).
//
// It generalizes licensecorpus.BuildCorpus over any closed string enum
// instead of repeating that package's shape nine more times: one must-pass
// case per member plus a must-fail negative, each carrying enum provenance
// and a non-empty mutation description, rendered as committed YAML corpora
// in the schema/testcase shape. cmd/gen-enum-corpora writes one committed
// artifact per enum under testdata/, and enumcorpus_test.go guards each with
// the same two tests licensecorpus.go documents: an exhaustive-coverage test
// that reddens if the enum widens without the corpus regenerated, and a
// freshness gate that reddens if the committed file drifts from a fresh
// render.
package enumcorpus

import (
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/peasant-labs/schema/testcase"
)

//go:generate go run github.com/peasant-labs/schema/cmd/gen-enum-corpora

// ClosedEnum is the constraint every corpus in this package operates over: a
// named string type carrying the module's standard IsValid/String
// closed-set methods.
type ClosedEnum interface {
	~string
	IsValid() bool
	String() string
}

// generatedHeader marks an artifact as generated so it is never hand-edited;
// the freshness gate enforces that. sourceRef names the Go inventory the
// corpus mirrors, so the "why did this go stale" trail points somewhere
// concrete.
func generatedHeader(sourceRef string) string {
	return "# Code generated by cmd/gen-enum-corpora; DO NOT EDIT.\n" +
		"# Regenerate: go generate ./... from the module root.\n" +
		"# Source of truth: " + sourceRef + ". Widening the set without\n" +
		"# regenerating this corpus reddens the exhaustive-coverage test.\n"
}

// BuildCorpus enumerates all into one must-pass case per member, then
// appends a single must-fail negative built from negative. Every case
// carries Source=SourceEnum, a concrete provenance ref, and a non-empty
// mutation description, so each case passes testcase.Case.Validate (never
// vacuous). Mirrors licensecorpus.BuildCorpus, generalized over any
// ClosedEnum.
func BuildCorpus[T ClosedEnum](enumName, sourceRef string, all []T, negative T, negativeReason string) testcase.Corpus[T, bool] {
	cases := make([]testcase.Case[T, bool], 0, len(all)+1)
	for _, value := range all {
		cases = append(cases, testcase.Case[T, bool]{
			Name:           enumName + " " + value.String() + " is valid",
			Input:          value,
			Expected:       true,
			Classification: testcase.MustPass,
			Provenance: testcase.Provenance{
				Source: testcase.SourceEnum,
				Ref:    sourceRef,
			},
			Mutation: testcase.Mutation{
				Description: "removing " + value.String() + " from " + sourceRef + " would reject a value the wire still accepts.",
			},
		})
	}
	cases = append(cases, testcase.Case[T, bool]{
		Name:           enumName + " outside the closed set is rejected",
		Input:          negative,
		Expected:       false,
		Classification: testcase.MustFail,
		Provenance: testcase.Provenance{
			Source: testcase.SourceEnum,
			Ref:    sourceRef,
		},
		Mutation: testcase.Mutation{Description: negativeReason},
	})
	return testcase.Corpus[T, bool]{Cases: cases}
}

// RenderCorpus returns the committed artifact bytes for a corpus built by
// BuildCorpus: the generated header followed by its YAML encoding. It is
// deterministic, so the freshness gate can byte-compare it against the
// committed file.
func RenderCorpus[T ClosedEnum](enumName, sourceRef string, all []T, negative T, negativeReason string) ([]byte, error) {
	corpus := BuildCorpus(enumName, sourceRef, all, negative, negativeReason)
	body, err := yaml.Marshal(corpus)
	if err != nil {
		return nil, fmt.Errorf("marshal %s corpus: %w", enumName, err)
	}
	return append([]byte(generatedHeader(sourceRef)), body...), nil
}
