// Code generated by go run ./cmd/schema-gen. DO NOT EDIT.
import type { CommitRef, SessionID, TimelineSessionRef } from "../index.js";
import { validateCorpus, type Case, type Classification, type Corpus } from "../testcase.js";

export type TimelineFixtureSessionInput = Omit<TimelineSessionRef, "harness"> & { harness: string };
export type TimelineFixtureCommitInput = Omit<CommitRef, "sessionIds"> & { sessionIds: SessionID[] | null };

export interface TimelineFixtureInput {
  sessions: TimelineFixtureSessionInput[];
  commits: TimelineFixtureCommitInput[];
}

export interface TimelineFixtureExpected {
  errorContains?: string;
}

export type TimelineFixtureCase = Case<TimelineFixtureInput, TimelineFixtureExpected>;
export type TimelineFixtureCorpus = Corpus<TimelineFixtureInput, TimelineFixtureExpected>;

export interface TimelineFixtureManifestEntry {
  family: string;
  name: string;
  classification: Classification;
}

export interface TimelineManifestMutationInput {
  kind: string;
  target: string;
  replacementName: string;
  replacementClassification: Classification;
}

export type TimelineManifestMutationCorpus = Corpus<TimelineManifestMutationInput, boolean>;

export interface TimelineFixtureManifest {
  cases: TimelineFixtureManifestEntry[];
  mutations: TimelineManifestMutationCorpus;
}

const canonicalTimelineFixtures: TimelineFixtureCorpus = {
  "cases": [
    {
      "name": "many_to_many_bindings",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "first task",
            "harness": "claude-code",
            "startMs": 2000,
            "hasCommitBinding": true
          },
          {
            "sessionId": "session-b",
            "title": "second task",
            "harness": "codex",
            "startMs": 1000,
            "hasCommitBinding": true
          }
        ],
        "commits": [
          {
            "hash": "commit-2",
            "subject": "follow-up",
            "hasSession": true,
            "sessionIds": [
              "session-a",
              "session-b"
            ]
          },
          {
            "hash": "commit-1",
            "subject": "setup",
            "hasSession": true,
            "sessionIds": [
              "session-a"
            ]
          }
        ]
      },
      "expected": {},
      "classification": "must-pass",
      "provenance": {
        "source": "requirement",
        "ref": "authoritative many-to-many commit bindings"
      },
      "mutation": {
        "description": "binds two sessions to one commit and one session to two commits"
      }
    },
    {
      "name": "session_not_linked_to_commit",
      "input": {
        "sessions": [
          {
            "sessionId": "session-unlinked",
            "title": "exploration",
            "harness": "opencode",
            "startMs": 3000,
            "hasCommitBinding": false
          }
        ],
        "commits": [
          {
            "hash": "commit-empty",
            "subject": "manual change",
            "hasSession": false,
            "sessionIds": []
          }
        ]
      },
      "expected": {},
      "classification": "must-pass",
      "provenance": {
        "source": "requirement",
        "ref": "unattached sessions remain discoverable"
      },
      "mutation": {
        "description": "includes a visible session with no commit association"
      }
    },
    {
      "name": "binding_outside_default_branch_window",
      "input": {
        "sessions": [
          {
            "sessionId": "session-old",
            "title": "older recorded work",
            "harness": "claude-code",
            "hasCommitBinding": true
          }
        ],
        "commits": [
          {
            "hash": "commit-recent",
            "subject": "recent manual change",
            "hasSession": false,
            "sessionIds": []
          }
        ]
      },
      "expected": {},
      "classification": "must-pass",
      "provenance": {
        "source": "requirement",
        "ref": "complete binding truth exceeds bounded commit window"
      },
      "mutation": {
        "description": "keeps binding truth when the associated commit is outside the returned window"
      }
    },
    {
      "name": "binding_on_non_default_branch",
      "input": {
        "sessions": [
          {
            "sessionId": "session-branch",
            "title": "branch work",
            "harness": "codex",
            "hasCommitBinding": true
          }
        ],
        "commits": []
      },
      "expected": {},
      "classification": "must-pass",
      "provenance": {
        "source": "requirement",
        "ref": "branch bindings are authoritative without inference"
      },
      "mutation": {
        "description": "keeps binding truth when no default-branch commit is visible"
      }
    },
    {
      "name": "stable_equal_timestamp_and_missing_timestamp_order",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "first tie",
            "harness": "claude-code",
            "startMs": 4000,
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-b",
            "title": "second tie",
            "harness": "codex",
            "startMs": 4000,
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-c",
            "title": "unknown time",
            "harness": "opencode",
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {},
      "classification": "must-pass",
      "provenance": {
        "source": "requirement",
        "ref": "deterministic session timeline ordering"
      },
      "mutation": {
        "description": "combines timestamp ties and a missing timestamp in canonical order"
      }
    },
    {
      "name": "newer_timestamp_must_precede_older",
      "input": {
        "sessions": [
          {
            "sessionId": "session-old",
            "title": "older",
            "harness": "claude-code",
            "startMs": 1000,
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-new",
            "title": "newer",
            "harness": "codex",
            "startMs": 2000,
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {
        "errorContains": "violate canonical ordering"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "descending known start timestamp order"
      },
      "mutation": {
        "description": "places a newer timestamp after an older timestamp"
      }
    },
    {
      "name": "equal_timestamp_uses_session_identity_tiebreak",
      "input": {
        "sessions": [
          {
            "sessionId": "session-b",
            "title": "second",
            "harness": "codex",
            "startMs": 3000,
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-a",
            "title": "first",
            "harness": "claude-code",
            "startMs": 3000,
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {
        "errorContains": "violate canonical ordering"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "stable equal-timestamp tie break"
      },
      "mutation": {
        "description": "reverses session identity order for equal timestamps"
      }
    },
    {
      "name": "missing_timestamp_follows_known_timestamp",
      "input": {
        "sessions": [
          {
            "sessionId": "session-unknown",
            "title": "unknown",
            "harness": "opencode",
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-known",
            "title": "known",
            "harness": "claude-code",
            "startMs": 3000,
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {
        "errorContains": "violate canonical ordering"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "missing timestamps sort after known timestamps"
      },
      "mutation": {
        "description": "places a missing timestamp before a known timestamp"
      }
    },
    {
      "name": "boolean_mirror_mismatch",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "work",
            "harness": "claude-code",
            "hasCommitBinding": true
          }
        ],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": false,
            "sessionIds": [
              "session-a"
            ]
          }
        ]
      },
      "expected": {
        "errorContains": "hasSession must mirror"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "requirement",
        "ref": "compatibility boolean mirrors authoritative bindings"
      },
      "mutation": {
        "description": "clears hasSession while retaining a session binding"
      }
    },
    {
      "name": "visible_reference_requires_complete_binding_truth",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "work",
            "harness": "claude-code",
            "hasCommitBinding": false
          }
        ],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": true,
            "sessionIds": [
              "session-a"
            ]
          }
        ]
      },
      "expected": {
        "errorContains": "hasCommitBinding=false"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "requirement",
        "ref": "visible binding proves complete session binding truth"
      },
      "mutation": {
        "description": "marks a visibly bound session as having no authoritative binding"
      }
    },
    {
      "name": "unknown_session_reference",
      "input": {
        "sessions": [],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": true,
            "sessionIds": [
              "session-missing"
            ]
          }
        ]
      },
      "expected": {
        "errorContains": "references unknown sessionId"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "requirement",
        "ref": "commit bindings reference normalized session identities"
      },
      "mutation": {
        "description": "points a commit binding at a session absent from the session catalog"
      }
    },
    {
      "name": "duplicate_session_identity",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "first",
            "harness": "claude-code",
            "hasCommitBinding": false
          },
          {
            "sessionId": "session-a",
            "title": "duplicate",
            "harness": "claude-code",
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {
        "errorContains": "duplicate timeline session"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "normalized session identity uniqueness"
      },
      "mutation": {
        "description": "repeats one session identity in the session catalog"
      }
    },
    {
      "name": "duplicate_binding",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "work",
            "harness": "claude-code",
            "hasCommitBinding": true
          }
        ],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": true,
            "sessionIds": [
              "session-a",
              "session-a"
            ]
          }
        ]
      },
      "expected": {
        "errorContains": "repeats sessionId"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "commit binding set uniqueness"
      },
      "mutation": {
        "description": "repeats one session identity in a commit binding list"
      }
    },
    {
      "name": "null_commit_bindings",
      "input": {
        "sessions": [],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": false,
            "sessionIds": null
          }
        ]
      },
      "expected": {
        "errorContains": "null sessionIds"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "non-null commit binding arrays"
      },
      "mutation": {
        "description": "omits the required sessionIds array from a commit"
      }
    },
    {
      "name": "unknown_timeline_harness",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "work",
            "harness": "unknown-harness",
            "hasCommitBinding": false
          }
        ],
        "commits": []
      },
      "expected": {
        "errorContains": "unknown harness"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "timeline sessions use the canonical harness closed set"
      },
      "mutation": {
        "description": "replaces a known harness with an unknown harness token"
      }
    },
    {
      "name": "noncanonical_binding_order",
      "input": {
        "sessions": [
          {
            "sessionId": "session-a",
            "title": "first",
            "harness": "claude-code",
            "startMs": 2000,
            "hasCommitBinding": true
          },
          {
            "sessionId": "session-b",
            "title": "second",
            "harness": "codex",
            "startMs": 1000,
            "hasCommitBinding": true
          }
        ],
        "commits": [
          {
            "hash": "commit-a",
            "subject": "work",
            "hasSession": true,
            "sessionIds": [
              "session-b",
              "session-a"
            ]
          }
        ]
      },
      "expected": {
        "errorContains": "noncanonical sessionIds order"
      },
      "classification": "must-fail",
      "provenance": {
        "source": "boundary",
        "ref": "commit bindings follow normalized timeline session rank"
      },
      "mutation": {
        "description": "reverses two valid bindings relative to the canonical session order"
      }
    }
  ]
};

const canonicalTimelineFixtureManifest: TimelineFixtureManifest = {
  "cases": [
    {
      "family": "many-to-many-bindings",
      "name": "many_to_many_bindings",
      "classification": "must-pass"
    },
    {
      "family": "unattached-session",
      "name": "session_not_linked_to_commit",
      "classification": "must-pass"
    },
    {
      "family": "binding-outside-window",
      "name": "binding_outside_default_branch_window",
      "classification": "must-pass"
    },
    {
      "family": "non-default-branch-binding",
      "name": "binding_on_non_default_branch",
      "classification": "must-pass"
    },
    {
      "family": "stable-session-order",
      "name": "stable_equal_timestamp_and_missing_timestamp_order",
      "classification": "must-pass"
    },
    {
      "family": "descending-timestamp-order",
      "name": "newer_timestamp_must_precede_older",
      "classification": "must-fail"
    },
    {
      "family": "equal-timestamp-tiebreak",
      "name": "equal_timestamp_uses_session_identity_tiebreak",
      "classification": "must-fail"
    },
    {
      "family": "missing-timestamp-order",
      "name": "missing_timestamp_follows_known_timestamp",
      "classification": "must-fail"
    },
    {
      "family": "compatibility-boolean",
      "name": "boolean_mirror_mismatch",
      "classification": "must-fail"
    },
    {
      "family": "complete-binding-truth",
      "name": "visible_reference_requires_complete_binding_truth",
      "classification": "must-fail"
    },
    {
      "family": "known-session-reference",
      "name": "unknown_session_reference",
      "classification": "must-fail"
    },
    {
      "family": "unique-session-identity",
      "name": "duplicate_session_identity",
      "classification": "must-fail"
    },
    {
      "family": "unique-commit-binding",
      "name": "duplicate_binding",
      "classification": "must-fail"
    },
    {
      "family": "non-null-commit-bindings",
      "name": "null_commit_bindings",
      "classification": "must-fail"
    },
    {
      "family": "known-harness",
      "name": "unknown_timeline_harness",
      "classification": "must-fail"
    },
    {
      "family": "canonical-binding-order",
      "name": "noncanonical_binding_order",
      "classification": "must-fail"
    }
  ],
  "mutations": {
    "cases": [
      {
        "name": "count_preserving_rename_is_rejected",
        "input": {
          "kind": "rename",
          "target": "many_to_many_bindings",
          "replacementName": "renamed_many_to_many_bindings",
          "replacementClassification": "must-pass"
        },
        "expected": false,
        "classification": "must-fail",
        "provenance": {
          "source": "boundary",
          "ref": "exact timeline family identity manifest"
        },
        "mutation": {
          "description": "renames one case without changing the corpus count"
        }
      },
      {
        "name": "count_preserving_replacement_is_rejected",
        "input": {
          "kind": "replace",
          "target": "noncanonical_binding_order",
          "replacementName": "filler_binding_case",
          "replacementClassification": "must-fail"
        },
        "expected": false,
        "classification": "must-fail",
        "provenance": {
          "source": "boundary",
          "ref": "exact timeline family identity manifest"
        },
        "mutation": {
          "description": "replaces one canonical family with a valid filler without changing the corpus count"
        }
      }
    ]
  }
};

export function loadTimelineFixtures(): TimelineFixtureCorpus { return structuredClone(canonicalTimelineFixtures); }
export function loadTimelineFixtureManifest(): TimelineFixtureManifest { return structuredClone(canonicalTimelineFixtureManifest); }

export function validateTimelineFixtureIdentity(fixtures: TimelineFixtureCorpus, manifest: TimelineFixtureManifest): Error | undefined {
  const corpusError = validateCorpus(fixtures);
  if (corpusError !== undefined) return corpusError;
  if (fixtures.cases.length !== manifest.cases.length) return new Error(`timeline corpus has ${fixtures.cases.length} cases, want exact manifest count ${manifest.cases.length}`);
  for (const [index, fixture] of fixtures.cases.entries()) {
    const identity = manifest.cases[index];
    if (identity === undefined || fixture.name !== identity.name || fixture.classification !== identity.classification) return new Error(`timeline case ${index} identity does not match canonical family manifest`);
  }
  return undefined;
}
